import type { EchoDef } from '../defs'
import { OBJECT_IDS } from '../types'
import { OBJECTS } from './objects'

/*
 * ECHOES — what happens when a borrowed thing goes out into Mosswick.
 *
 * Resolution picks the highest-priority Echo whose conditions hold.
 * Rough priority bands:
 *   90+   story unlocks (the Glasshouse door)
 *   78–89 provenance payoffs: only possible because of what an object remembers
 *   55–76 resident-specific scenes
 *   62    generic "trace" scenes: finding what the previous borrower left behind
 *   36–44 weather-shaped scenes
 *   20–25 social fallbacks (meet someone new)
 *   10    solo fallbacks — every object always has one
 *
 * Templates: {name} {they} {them} {their} {They} {Their} {other} {NAME} {OTHER}
 *            {obj} {Obj} {place} {keepsake} {mark} {latest} {photoCount}
 */

const telescope: EchoDef[] = [
  {
    id: 'tele_saturn',
    object: 'telescope',
    clearNight: true,
    history: { tag: 'stargazing', by: 'other' },
    other: { kind: 'prev', tag: 'stargazing' },
    priority: 88,
    once: true,
    title: 'Saturn Has Rings!',
    text: '{name} climbed the Hill and found {other} already up there, squinting at the sky with bare eyes. “I saw something through that telescope,” {other} said. They took turns. At fourteen minutes past nine {name} found Saturn, and they both said “it has RINGS” at exactly the same time, as if the other might not have heard.',
    mark: 'saturnSticker',
    tags: ['stargazing', 'saturn'],
    flagsSet: ['saturn_seen'],
  },
  {
    id: 'tele_tobias_stickers',
    object: 'telescope',
    resident: 'tobias',
    clearNight: true,
    notFlags: ['tobias_hettie_star'],
    other: { kind: 'trace' },
    priority: 84,
    once: true,
    title: 'Hettie’s Star',
    text: 'Tobias hadn’t looked through his old telescope since Hettie. He carried it up the Hill in three stages and found her favourite star — a dim one; she said that was the point. Then he noticed {other}’s {mark} on the barrel and laughed out loud, the first time anyone had heard him laugh on the Hill in years. He went round to {other}’s next morning to say thank you for looking after it.',
    mark: 'ribbon',
    markNote: 'tied on by T.C.',
    tags: ['stargazing', 'memory'],
    flagsSet: ['tobias_hettie_star'],
  },
  {
    id: 'tele_odile_moon',
    object: 'telescope',
    resident: 'odile',
    requests: ['odile_moon'],
    clearNight: true,
    other: { kind: 'resident', id: 'tansy' },
    priority: 82,
    once: true,
    title: 'Is It Getting My Letters?',
    text: 'Odile took the telescope and the latest letter up the Hill, meaning to read it to the Moon, officially. Instead she found Tansy up there, shivering bravely, and let her look first. “Is it getting my letters?” Tansy asked. “I’m looking into it,” said Odile.',
    mark: 'moonSticker',
    tags: ['stargazing'],
    flagsSet: ['moon_letter_seed', 'tansy_stargazed'],
  },
  {
    id: 'tele_shared',
    object: 'telescope',
    clearNight: true,
    flags: ['saturn_seen'],
    history: { tag: 'stargazing', by: 'other' },
    other: { kind: 'prev', tag: 'stargazing' },
    priority: 74,
    once: true,
    title: 'Room for Two on the Hill',
    text: 'The telescope knew the way by now. {name} found {other} on the Hill, just where {other} had been the last time it came up here, and they spent the evening arguing pleasantly about which dot was Jupiter.',
    mark: 'starSticker',
    tags: ['stargazing'],
  },
  {
    id: 'tele_tansy_first',
    object: 'telescope',
    resident: 'tansy',
    clearNight: true,
    priority: 70,
    once: true,
    title: 'The Moon, Properly',
    text: 'Tansy lugged the telescope up Observatory Hill and found the Moon on the third try. She said “oh” so loudly that a sheep on the next hill looked up. It got very dark, very fast, so she came home early — but she came home with a star sticker on the barrel and a list of questions.',
    mark: 'starSticker',
    tags: ['stargazing'],
    flagsSet: ['tansy_stargazed'],
  },
  {
    id: 'tele_tansy_cloudy',
    object: 'telescope',
    resident: 'tansy',
    clearNight: false,
    priority: 68,
    once: true,
    title: 'Eleven Seconds of Moon',
    text: 'Tansy watched the clouds from the Hill all evening, telescope ready, like a cat at a mousehole. The Moon came out for eleven seconds. She counted. She says eleven seconds is plenty, if you’re paying attention.',
    mark: 'moonSticker',
    tags: ['stargazing'],
    flagsSet: ['tansy_stargazed'],
  },
  {
    id: 'tele_hollis',
    object: 'telescope',
    resident: 'hollis',
    clearNight: true,
    other: { kind: 'any' },
    priority: 66,
    once: true,
    title: 'Describe It to Me',
    text: 'Moles are not built for telescopes. So Hollis pointed it at the sky and asked passers-by to describe what they saw. By ten o’clock he had a small crowd, and {other} was explaining Jupiter as “a sort of bright button.” Hollis has written that down on his map.',
    mark: 'label',
    markNote: 'Jupiter: a bright button',
    tags: ['stargazing'],
  },
  {
    id: 'tele_tobias',
    object: 'telescope',
    resident: 'tobias',
    clearNight: true,
    notFlags: ['tobias_hettie_star'],
    priority: 66,
    once: true,
    title: 'Hettie’s Star',
    text: 'Tobias hadn’t looked through his old telescope since Hettie. He carried it up the Hill in three stages, found her favourite star — a dim one; she said that was the point — and sat with it for a while. He came down humming.',
    mark: 'ribbon',
    markNote: 'tied on by T.C.',
    tags: ['stargazing', 'memory'],
    flagsSet: ['tobias_hettie_star'],
  },
  {
    id: 'tele_tobias_cloudy',
    object: 'telescope',
    resident: 'tobias',
    clearNight: false,
    priority: 62,
    once: true,
    title: 'Somewhere Up There',
    text: 'Tobias carried the telescope up the Hill in three stages and found nothing but cloud. He sat on the bench anyway and told the clouds about Hettie’s star, since it was up there somewhere behind them.',
    mark: 'ribbon',
    markNote: 'tied on by T.C.',
    tags: ['memory'],
  },
  {
    id: 'tele_odile',
    object: 'telescope',
    resident: 'odile',
    clearNight: true,
    priority: 60,
    once: true,
    title: 'Off Duty, Looking Up',
    text: 'Odile set the telescope up with military precision and then simply looked, for two hours, at nothing in particular. She has not done nothing in particular in years. She would like to do it again.',
    mark: 'starSticker',
    tags: ['stargazing'],
    flagsSet: ['odile_rested'],
  },
  {
    id: 'tele_barnaby',
    object: 'telescope',
    resident: 'barnaby',
    clearNight: true,
    priority: 60,
    once: true,
    title: 'The Moon Looks Like a Crumpet',
    text: 'Barnaby looked at the Moon properly for the first time in his life and said, with real feeling, that it looked like a crumpet. He was up at four the next morning, experimenting.',
    mark: 'flourPrint',
    tags: ['stargazing'],
    flagsSet: ['moon_crumpets'],
  },
  {
    id: 'tele_margo',
    object: 'telescope',
    resident: 'margo',
    clearNight: true,
    priority: 60,
    once: true,
    title: 'Frost on the Moon',
    text: 'Margo used the telescope to check the Moon for frost, which she says is “a thing.” It is not a thing. She wrote four lines about it anyway, then four more, then hid them in a seed tray.',
    mark: 'label',
    markNote: '(not a poem)',
    tags: ['stargazing'],
    flagsSet: ['margo_poem'],
  },
  {
    id: 'tele_cloudy',
    object: 'telescope',
    clearNight: false,
    priority: 40,
    title: 'Mostly Cloud',
    text: '{name} set the telescope up on the Hill and got a very detailed view of a cloud. Then, through a gap, for about a minute: one enormous bright star. {They} decided that counted.',
    mark: 'label',
    markNote: 'mostly cloud (lovely)',
    tags: ['cloudwatch'],
  },
  {
    id: 'tele_social',
    chance: 0.5,
    object: 'telescope',
    clearNight: true,
    other: { kind: 'any' },
    priority: 25,
    title: 'A Smaller Plough',
    text: 'Halfway up the Hill with the telescope, {name} met {other} coming down with nothing much to do. {other} came back up. They found the Plough, then a smaller plough, then argued about whether that was a plough at all.',
    mark: 'starSticker',
    tags: ['stargazing'],
  },
  {
    id: 'tele_solo',
    object: 'telescope',
    priority: 10,
    title: 'Until the Dew Came Down',
    text: '{name} took the telescope up Observatory Hill and stayed until the dew came down: the Moon’s craters, a blinking satellite, and one shooting star {they} have decided not to tell anyone about.',
    mark: 'starSticker',
    tags: ['stargazing'],
  },
]

const blanket: EchoDef[] = [
  {
    id: 'blanket_hollis',
    object: 'blanket',
    resident: 'hollis',
    notWeather: ['rainy'],
    other: { kind: 'any' },
    priority: 66,
    once: true,
    location: 'green',
    title: 'An Invitation You Can Walk Into',
    text: 'Hollis laid the blanket out in the middle of the Green, sat on one corner and waited, like an invitation you could walk into. By two o’clock {other} had walked into it, with biscuits.',
    mark: 'jamStain',
    tags: ['picnic'],
  },
  {
    id: 'blanket_barnaby',
    object: 'blanket',
    resident: 'barnaby',
    weather: ['sunny', 'foggy'],
    other: { kind: 'resident', id: 'margo' },
    priority: 64,
    once: true,
    title: 'Is That a Marrow Sandwich?',
    text: 'Barnaby spread the blanket by the Millpond and lay on it for an entire afternoon, like people in paintings. Margo walked past, stopped, and said, “Is that a marrow sandwich?” It was. Truce talks are ongoing.',
    mark: 'grassStain',
    tags: ['picnic', 'marrow'],
  },
  {
    id: 'blanket_odile',
    object: 'blanket',
    resident: 'odile',
    notWeather: ['rainy'],
    priority: 62,
    once: true,
    title: 'Without the Satchel',
    text: 'Odile sat on the blanket by the Millpond without her satchel for the first time in living memory. She kept reaching for it. By the end of the afternoon, she had stopped reaching.',
    mark: 'clover',
    tags: ['picnic', 'rest'],
    flagsSet: ['odile_rested'],
  },
  {
    id: 'blanket_tobias',
    object: 'blanket',
    resident: 'tobias',
    notWeather: ['rainy'],
    other: { kind: 'any' },
    priority: 62,
    once: true,
    location: 'green',
    title: 'The Hat',
    text: 'Tobias lowered himself onto the blanket on the Green in six careful stages and fell asleep in the sun. {other} put a hat on him so he wouldn’t burn. He woke up wearing it and has decided it is his now.',
    mark: 'clover',
    tags: ['picnic', 'rest'],
  },
  {
    id: 'blanket_tansy_wind',
    object: 'blanket',
    resident: 'tansy',
    weather: ['windy'],
    priority: 62,
    once: true,
    location: 'green',
    title: 'The Red-Checked Ghost',
    text: 'The wind got under the blanket, and so did Tansy, and for one glorious minute she was a red-checked ghost haunting the Green. Several people screamed. On purpose, to be nice.',
    mark: 'grassStain',
    tags: ['play'],
  },
  {
    id: 'blanket_margo',
    object: 'blanket',
    resident: 'margo',
    notWeather: ['rainy'],
    other: { kind: 'any' },
    priority: 60,
    once: true,
    title: 'Crisps Are Not a Food Group',
    text: 'Margo took the blanket to the Millpond and arranged the picnic by food group. {other} arrived with crisps, which are not a food group, and was allowed to stay anyway.',
    mark: 'jamStain',
    tags: ['picnic'],
  },
  {
    id: 'blanket_tansy',
    object: 'blanket',
    resident: 'tansy',
    notWeather: ['rainy'],
    other: { kind: 'any' },
    priority: 58,
    once: true,
    title: 'Base Camp',
    text: 'Tansy turned the blanket into Base Camp at the Millpond, with a flag, a password and a strict entry fee of one biscuit. {other} paid it, and was immediately made Deputy.',
    mark: 'jamStain',
    tags: ['picnic', 'play'],
  },
  {
    id: 'blanket_wind',
    object: 'blanket',
    weather: ['windy'],
    other: { kind: 'any' },
    priority: 42,
    location: 'green',
    title: 'One Corner Each',
    text: 'The wind had opinions about {name}’s picnic. {name} chased the blanket halfway across the Green; {other} caught it. They ate lunch sitting on it very firmly, one corner each.',
    mark: 'grassStain',
    tags: ['picnic'],
  },
  {
    id: 'blanket_rain',
    object: 'blanket',
    weather: ['rainy'],
    other: { kind: 'any' },
    priority: 42,
    location: 'green',
    title: 'Under the Bandstand',
    text: '{name} held a picnic under the bandstand roof with the rain drumming overhead. {other} dashed in to shelter and stayed for the sandwiches, which is the whole point of sandwiches.',
    mark: 'mudSplash',
    tags: ['picnic'],
  },
  {
    id: 'blanket_fog',
    object: 'blanket',
    weather: ['foggy'],
    priority: 40,
    title: 'Rude Waiters',
    text: '{name} had a picnic in the fog by the Millpond. Ducks kept appearing out of nowhere, like rude waiters.',
    mark: 'clover',
    tags: ['picnic'],
  },
  {
    id: 'blanket_social',
    chance: 0.5,
    object: 'blanket',
    notWeather: ['rainy'],
    other: { kind: 'any' },
    priority: 22,
    title: 'Half a Sandwich',
    text: '{name} spread the blanket at the Millpond and ate lunch at a slower pace than usual. {other} wandered past and was offered half a sandwich, which is how these things start.',
    mark: 'jamStain',
    tags: ['picnic'],
  },
  {
    id: 'blanket_solo',
    object: 'blanket',
    priority: 10,
    title: 'Absolutely Nothing, Beautifully',
    text: '{name} spread the blanket in the best spot {they} could find and did absolutely nothing, beautifully.',
    mark: 'grassStain',
    tags: ['picnic'],
  },
]

const camera: EchoDef[] = [
  {
    id: 'cam_barnaby',
    object: 'camera',
    resident: 'barnaby',
    other: { kind: 'resident', id: 'odile' },
    priority: 72,
    once: true,
    location: 'green',
    title: 'The Only Photograph of Odile',
    text: 'Barnaby photographed his loaves from “their good side,” then felt silly and photographed the Green instead. Odile walked into the frame. It is the only picture of her anyone has: mid-stride, faintly outraged. He has had it framed.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['photo'],
    flagsSet: ['barnaby_photo_odile'],
  },
  {
    id: 'cam_tansy_moon_sharp',
    object: 'camera',
    resident: 'tansy',
    requestTags: ['sky', 'night'],
    flags: ['camera_fixed'],
    priority: 72,
    once: true,
    location: 'kettleRow',
    time: 'night',
    title: 'Gerald, in Focus',
    text: 'Tansy photographed the Moon from her bedroom window eleven times, and because Tobias had fixed the sticky shutter, one came out crisp as a coin. She has named it Gerald. It lives under her pillow.',
    keepsake: { text: 'the Moon, crisp as a coin (Gerald)', place: 'kettleRow' },
    mark: 'moonSticker',
    tags: ['photo', 'moon'],
    flagsSet: ['tansy_stargazed', 'gerald'],
  },
  {
    id: 'cam_tansy_moon',
    object: 'camera',
    resident: 'tansy',
    requestTags: ['sky', 'night'],
    notFlags: ['camera_fixed', 'gerald'],
    priority: 70,
    once: true,
    location: 'kettleRow',
    time: 'night',
    title: 'A Smudge Named Gerald',
    text: 'Tansy took eleven photographs of the Moon from her bedroom window. They are all of a small white smudge. She has named the smudge Gerald and is extremely proud of him.',
    keepsake: true,
    mark: 'doodle',
    tags: ['photo', 'moon'],
    flagsSet: ['tansy_stargazed', 'gerald'],
  },
  {
    id: 'cam_margo',
    object: 'camera',
    resident: 'margo',
    other: { kind: 'resident', id: 'barnaby' },
    priority: 66,
    once: true,
    location: 'green',
    title: 'For Scale',
    text: 'Margo photographed her marrow next to a ruler, then next to Barnaby’s marrow, then next to Barnaby, for scale. Barnaby demanded a rematch photograph. They took nine. Neither will admit how much fun it was.',
    keepsake: true,
    mark: 'grassStain',
    tags: ['photo', 'marrow'],
  },
  {
    id: 'cam_tobias',
    object: 'camera',
    resident: 'tobias',
    priority: 66,
    once: true,
    location: 'kettleRow',
    title: 'Minus One Lamppost',
    text: 'Before taking a single picture, Tobias fixed the camera’s sticky shutter. Then he photographed Kettle Row exactly as it looked when he was a boy, minus one lamppost.',
    keepsake: true,
    mark: 'label',
    markNote: 'shutter fixed — T.C.',
    tags: ['photo', 'repair'],
    flagsSet: ['camera_fixed'],
  },
  {
    id: 'cam_hollis',
    object: 'camera',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 66,
    once: true,
    location: 'green',
    title: 'Asking Permission Afterwards',
    text: 'Hollis photographed every front door on the Green for his map, then knocked on each one to ask permission afterwards. That is how he met {other}, who said yes and asked for a copy.',
    keepsake: true,
    mark: 'label',
    markNote: 'for the map — H.U.',
    tags: ['photo', 'map'],
  },
  {
    id: 'cam_tansy',
    object: 'camera',
    resident: 'tansy',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    location: 'millpond',
    title: 'Definitely Something',
    text: 'Tansy photographed the thing under the jetty. The photo is a blur with, possibly, a face. She has shown it to everyone as proof. {other} agreed it was “definitely something,” which was the right answer.',
    keepsake: { text: 'the Thing Under the Jetty (a blur, possibly with a face)', place: 'millpond' },
    mark: 'mudSplash',
    tags: ['photo'],
  },
  {
    id: 'cam_odile',
    object: 'camera',
    resident: 'odile',
    priority: 62,
    once: true,
    location: 'green',
    title: 'From the Post Office Roof',
    text: 'Odile photographed Mosswick from the post office roof, which she has a key to and nobody else knows about. It is the only photograph of the whole village ever taken. She would like it back afterwards.',
    keepsake: true,
    mark: 'label',
    markNote: 'please return photo — O.F.',
    tags: ['photo'],
  },
  {
    id: 'cam_barnaby_solo',
    object: 'camera',
    resident: 'barnaby',
    priority: 56,
    once: true,
    location: 'green',
    title: 'Loaves, From Their Good Side',
    text: 'Barnaby photographed every loaf in the bakery from its good side. Then the bakery. Then, for reasons he cannot explain, the post office door at nine o’clock exactly.',
    keepsake: { text: 'the post office door, 9am exactly', place: 'green' },
    mark: 'flourPrint',
    tags: ['photo'],
  },
  {
    id: 'cam_wind',
    object: 'camera',
    weather: ['windy'],
    other: { kind: 'any' },
    priority: 42,
    location: 'green',
    title: 'Hat, Mid-Escape',
    text: '{name} spent the afternoon photographing leaves blowing across the Green. Most of the photographs are of nothing. One is of {other}’s hat, mid-escape, with {other} in hot pursuit.',
    keepsake: { text: '{other}’s hat, mid-escape', subject: 'other' },
    mark: 'leaf',
    tags: ['photo'],
  },
  {
    id: 'cam_rain',
    object: 'camera',
    weather: ['rainy'],
    priority: 42,
    location: 'kettleRow',
    title: 'Upside Down in a Puddle',
    text: '{name} photographed puddles on Kettle Row. In one of them, upside down and perfectly still, is the whole village.',
    keepsake: { text: 'the whole village, upside down in a puddle' },
    mark: 'mudSplash',
    tags: ['photo'],
  },
  {
    id: 'cam_fog',
    object: 'camera',
    weather: ['foggy'],
    priority: 40,
    location: 'millpond',
    title: 'Ducks, Like a Band',
    text: '{name} took the camera into the fog by the Millpond. Every photograph is white, except one, which has three ducks in it, looking directly at the camera, like a band.',
    keepsake: { text: 'three ducks in the fog, like a band' },
    mark: 'label',
    markNote: 'ducks (in fog)',
    tags: ['photo'],
  },
  {
    id: 'cam_social',
    chance: 0.5,
    object: 'camera',
    other: { kind: 'any' },
    priority: 22,
    title: 'Something Just Out of Frame',
    text: '{name} wandered Mosswick with the camera, photographing small things: a cat on a wall, a teacup, and {other}, laughing at something just out of frame.',
    keepsake: { text: '{other}, laughing at something just out of frame', subject: 'other' },
    mark: 'scratch',
    tags: ['photo'],
  },
  {
    id: 'cam_solo',
    object: 'camera',
    priority: 10,
    title: 'The One Good One',
    text: '{name} took photographs all afternoon and came back with one good one: {place} in the late light.',
    keepsake: { text: '{place} in the late light' },
    mark: 'scratch',
    tags: ['photo'],
  },
]

const recordPlayer: EchoDef[] = [
  {
    id: 'rec_barnaby_waltz',
    object: 'recordPlayer',
    resident: 'barnaby',
    other: { kind: 'trace', by: 'tobias', keepsakeOnly: true },
    priority: 86,
    once: true,
    title: 'The Hollyhock Waltz',
    text: 'In the lid of the record player, Barnaby found Tobias’s old Hollyhock Waltz, and remembered Tobias dancing at the Harvest Supper in 1974 with Hettie, both of them laughing. He took the record round to Tobias personally. They did not dance. They very nearly did.',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music', 'memory'],
  },
  {
    id: 'rec_dance',
    object: 'recordPlayer',
    weather: ['sunny', 'windy'],
    history: { tag: 'music', by: 'other', min: 2 },
    other: { kind: 'any' },
    priority: 76,
    once: true,
    location: 'green',
    time: 'dusk',
    indoor: false,
    title: 'Dancing on the Green',
    text: '{name} carried the record player onto the Green and put on whatever was in the lid — {latest}. Somehow half of Mosswick ended up dancing, including {other}, who famously does not dance.',
    keepsake: true,
    mark: 'grassStain',
    tags: ['music', 'dance'],
    flagsSet: ['dance_on_green'],
  },
  {
    id: 'rec_hollis_host',
    object: 'recordPlayer',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 70,
    once: true,
    title: 'The Music Did the Knocking',
    text: 'Hollis put a record on with his front door open and let the music do the knocking for him. {other} came in “for a minute.” It was three hours.',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music', 'host'],
  },
  {
    id: 'rec_tobias',
    object: 'recordPlayer',
    resident: 'tobias',
    notFlags: ['tobias_waltz'],
    other: { kind: 'resident', id: 'tansy' },
    priority: 68,
    once: true,
    location: 'kettleRow',
    indoor: false,
    title: 'What Tansy Called the Waltz',
    text: 'Tobias played the Hollyhock Waltz with the windows open. By the second chorus, Tansy was out on the pavement doing what she called “the waltz” and what Tobias called “very good indeed.”',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music', 'dance'],
    flagsSet: ['tobias_waltz'],
  },
  {
    id: 'rec_tansy',
    object: 'recordPlayer',
    resident: 'tansy',
    other: { kind: 'resident', id: 'tobias' },
    priority: 64,
    once: true,
    title: 'Sounds of Outer Space',
    text: 'Tansy played “Sounds of Outer Space, for Children” at full volume. Tobias, next door, said it was the best thing he’d heard in years, then asked what it was, then asked her to play it again.',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music'],
  },
  {
    id: 'rec_odile_rain',
    object: 'recordPlayer',
    resident: 'odile',
    weather: ['rainy', 'foggy'],
    other: { kind: 'any' },
    priority: 64,
    once: true,
    title: 'Songs About Fog',
    text: 'Odile played sea songs, mostly about fog, while her socks dried on the fender. She had meant to be alone. {other} knocked about a parcel and stayed for both sides.',
    keepsake: true,
    mark: 'teaRing',
    tags: ['music'],
  },
  {
    id: 'rec_margo',
    object: 'recordPlayer',
    resident: 'margo',
    other: { kind: 'any' },
    priority: 60,
    once: true,
    title: 'Madrigals for Seedlings',
    text: 'Margo played madrigals to her seedlings, who responded well. She says. She put a chair out for {other}, who came to listen and stayed to repot things.',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music'],
  },
  {
    id: 'rec_barnaby',
    object: 'recordPlayer',
    resident: 'barnaby',
    other: { kind: 'any' },
    priority: 60,
    once: true,
    title: 'Rising Out of Enthusiasm',
    text: 'Barnaby played brass band music in the bakery until the loaves rose out of sheer enthusiasm. Customers stayed longer than usual. {other} stayed longest.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['music'],
  },
  {
    id: 'rec_tobias_solo',
    object: 'recordPlayer',
    resident: 'tobias',
    notFlags: ['tobias_waltz'],
    priority: 58,
    once: true,
    title: 'A Dance With the Hatstand',
    text: 'Tobias played the Hollyhock Waltz three times with the windows open, and danced once, slowly, with the hatstand. He left the record in the lid, in case somebody else needs it.',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music', 'dance'],
    flagsSet: ['tobias_waltz'],
  },
  {
    id: 'rec_odile',
    object: 'recordPlayer',
    resident: 'odile',
    priority: 58,
    once: true,
    title: 'The Post Office, After Hours',
    text: 'Odile played her record in the empty post office after hours and, when nobody was looking, conducted it with a letter-opener.',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music'],
  },
  {
    id: 'rec_social',
    chance: 0.5,
    object: 'recordPlayer',
    other: { kind: 'any' },
    priority: 22,
    title: 'Through the Window',
    text: '{name} wound up the record player and put on whatever was in the lid. {other} heard it through the window and came to see what it was.',
    keepsake: true,
    mark: 'noteSticker',
    tags: ['music'],
  },
  {
    id: 'rec_solo',
    object: 'recordPlayer',
    priority: 10,
    title: 'Back to the Good Bit',
    text: '{name} spent the evening with the record player, lifting the needle back to the good bit, over and over.',
    keepsake: true,
    mark: 'scratch',
    tags: ['music'],
  },
]

const cakeTin: EchoDef[] = [
  {
    id: 'tin_odile_birthday',
    object: 'cakeTin',
    resident: 'odile',
    requests: ['odile_birthday'],
    other: { kind: 'resident', id: 'barnaby' },
    priority: 95,
    once: true,
    location: 'green',
    title: 'Why the Cake Sank',
    text: 'Odile baked her own birthday cake, because that is the sort of thing Odile does. Then she took it to the bakery to ask Barnaby why it had sunk in the middle. He worked out why she was baking. The bakery shut early. There were candles.',
    keepsake: true,
    mark: 'ribbon',
    tags: ['baking', 'birthday'],
    flagsSet: ['odile_birthday_party'],
  },
  {
    id: 'tin_odile_lemon',
    object: 'cakeTin',
    resident: 'odile',
    other: { kind: 'trace', by: 'barnaby', keepsakeOnly: true },
    priority: 86,
    once: true,
    title: 'More Lemon',
    text: 'On the recipe card in the tin, Odile found a note: “More lemon. MORE. — B.H.” She baked the cake with more lemon, as instructed, and took Barnaby a slice. He said it was better than his. He was lying. She could tell. She was delighted.',
    keepsake: true,
    mark: 'jamStain',
    tags: ['baking'],
    flagsSet: ['odile_cake_barnaby'],
  },
  {
    id: 'tin_barnaby_odile',
    object: 'cakeTin',
    resident: 'barnaby',
    requestTags: ['courage'],
    other: { kind: 'resident', id: 'odile' },
    priority: 78,
    once: true,
    location: 'green',
    title: 'A Floury Pawprint',
    text: 'Barnaby baked a small, perfect lemon cake and left it on the post office counter with no note. Odile knew exactly who it was from: there was a floury pawprint on the lid.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['baking', 'gift'],
    flagsSet: ['barnaby_cake_odile'],
  },
  {
    id: 'tin_hollis',
    object: 'cakeTin',
    resident: 'hollis',
    other: { kind: 'any', prefer: ['tobias', 'tansy'] },
    priority: 70,
    once: true,
    location: 'kettleRow',
    indoor: false,
    title: 'Directions to the Good Bench',
    text: 'Hollis baked a slightly crooked sponge and took a slice to every door on Kettle Row. {other} gave him a jar of jam in return, and directions to the good bench.',
    keepsake: true,
    mark: 'jamStain',
    tags: ['baking', 'gift'],
  },
  {
    id: 'tin_barnaby_revised',
    object: 'cakeTin',
    resident: 'barnaby',
    notFlags: ['barnaby_new_recipe'],
    other: { kind: 'resident', id: 'tobias' },
    priority: 68,
    once: true,
    title: 'Lemon Drizzle, Revised',
    text: 'Barnaby followed the old recipe card in the tin, argued with it in the margins, and then baked something new for the first time in eleven years. He took a slice to Tobias, who said it was “different,” which from Tobias is a medal.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['baking'],
    flagsSet: ['barnaby_new_recipe'],
  },
  {
    id: 'tin_margo',
    object: 'cakeTin',
    resident: 'margo',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    title: 'Tell No One',
    text: 'Margo baked a courgette cake, told no one it had courgette in it, and took it to the thing with people. It was the first thing to go. {other} asked for the recipe. Margo said “no,” and then wrote it down for them.',
    keepsake: true,
    mark: 'jamStain',
    tags: ['baking', 'gift'],
  },
  {
    id: 'tin_tobias',
    object: 'cakeTin',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    title: 'Too Much Cake for One',
    text: 'Tobias baked Hettie’s recipe from memory, pinch of salt and all, and carried the tin round to {other}’s. “Too much cake for one,” he said, which was true, because he had made sure of it.',
    keepsake: true,
    mark: 'dent',
    tags: ['baking', 'memory'],
  },
  {
    id: 'tin_barnaby_revised_solo',
    object: 'cakeTin',
    resident: 'barnaby',
    notFlags: ['barnaby_new_recipe'],
    priority: 60,
    once: true,
    title: 'Lemon Drizzle, Revised',
    text: 'Barnaby followed the old recipe card in the tin, argued with it in the margins, and then baked something new for the first time in eleven years. He called it “Lemon Drizzle, Revised” and was unbearable about it all day.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['baking'],
    flagsSet: ['barnaby_new_recipe'],
  },
  {
    id: 'tin_tansy',
    object: 'cakeTin',
    resident: 'tansy',
    other: { kind: 'any' },
    priority: 60,
    once: true,
    title: 'Structurally Sprinkles',
    text: 'Tansy baked a cake with all of the sprinkles. It was, structurally, more sprinkle than cake. She gave a slice to {other}, who ate the whole thing with enormous courage.',
    keepsake: true,
    mark: 'jamStain',
    tags: ['baking', 'gift'],
  },
  {
    id: 'tin_social',
    chance: 0.5,
    object: 'cakeTin',
    other: { kind: 'any' },
    priority: 22,
    title: 'Practically the Law',
    text: '{name} baked something in the old tin and took it round to {other}’s while it was still warm. Nobody has ever refused a warm cake. It is practically the law.',
    keepsake: true,
    mark: 'jamStain',
    tags: ['baking'],
  },
  {
    id: 'tin_solo',
    object: 'cakeTin',
    priority: 10,
    title: 'Standing Up in the Kitchen',
    text: '{name} baked in the old tin and ate the first slice standing up in the kitchen, which is the best way.',
    keepsake: true,
    mark: 'jamStain',
    tags: ['baking'],
  },
]

const kite: EchoDef[] = [
  {
    id: 'kite_oak',
    object: 'kite',
    weather: ['windy'],
    notResident: ['odile'],
    other: { kind: 'resident', id: 'odile' },
    priority: 72,
    once: true,
    title: 'The Old Oak Keeps Things',
    text: 'The kite went up beautifully, and then into the Old Oak on the Hill, where it stayed. Odile, passing with the post, reached up and plucked it out — she is the only one in Mosswick tall enough. {name} said thank you four times.',
    mark: 'leaf',
    tags: ['kite', 'oak'],
  },
  {
    id: 'kite_odile',
    object: 'kite',
    resident: 'odile',
    weather: ['windy'],
    other: { kind: 'resident', id: 'tansy' },
    priority: 70,
    once: true,
    title: 'Herons Are Built for It',
    text: 'Odile had never flown a kite. It turns out herons are built for it: long legs, long patience. Tansy watched from the fence for an hour before asking for a go, and was given one, with instructions.',
    mark: 'feather',
    tags: ['kite'],
    flagsSet: ['odile_kite'],
  },
  {
    id: 'kite_margo',
    object: 'kite',
    resident: 'margo',
    weather: ['windy'],
    other: { kind: 'resident', id: 'barnaby' },
    priority: 66,
    once: true,
    title: 'Barnaby for Applause',
    text: 'Margo flew the kite as if it had personally insulted her beans. It went higher than anyone has ever flown it. Barnaby, watching from the stile, said nothing at all, which is Barnaby for applause.',
    mark: 'knot',
    tags: ['kite'],
  },
  {
    id: 'kite_hollis',
    object: 'kite',
    resident: 'hollis',
    weather: ['windy'],
    other: { kind: 'any' },
    priority: 64,
    once: true,
    title: 'Flying by Feel',
    text: 'Hollis couldn’t see the kite once it was up, so he flew it by feel, reporting every tug like a fisherman. {other} narrated. Between them, they did very well.',
    mark: 'knot',
    tags: ['kite'],
  },
  {
    id: 'kite_tansy',
    object: 'kite',
    resident: 'tansy',
    weather: ['windy'],
    priority: 62,
    once: true,
    title: 'A Dot With Opinions',
    text: 'Tansy flew the kite until it was a red dot, then a redder dot, then a dot with opinions. She came home windswept and hoarse from shouting “HIGHER” at it.',
    mark: 'knot',
    tags: ['kite'],
  },
  {
    id: 'kite_odile_solo',
    object: 'kite',
    resident: 'odile',
    weather: ['windy'],
    notFlags: ['odile_kite'],
    priority: 60,
    once: true,
    title: 'Herons Are Built for It',
    text: 'Odile had never flown a kite. It turns out herons are built for it: long legs, long patience. She flew it for two hours without once checking the time.',
    mark: 'feather',
    tags: ['kite'],
    flagsSet: ['odile_kite', 'odile_rested'],
  },
  {
    id: 'kite_barnaby',
    object: 'kite',
    resident: 'barnaby',
    weather: ['windy'],
    priority: 60,
    once: true,
    title: 'Snow Over Mosswick',
    text: 'Barnaby flew the kite from the top of the Hill with flour still all over his apron, so for a while it snowed, very slightly, over Mosswick.',
    mark: 'flourPrint',
    tags: ['kite'],
  },
  {
    id: 'kite_tobias',
    object: 'kite',
    resident: 'tobias',
    weather: ['windy'],
    priority: 60,
    once: true,
    title: 'The Secret to Most Things',
    text: 'Tobias flew the kite sitting down on the bench at the top of the Hill, with enormous dignity. The kite did all the work. He says that is the secret to most things.',
    mark: 'ribbon',
    tags: ['kite'],
  },
  {
    id: 'kite_still',
    object: 'kite',
    notWeather: ['windy', 'rainy'],
    other: { kind: 'any' },
    priority: 44,
    location: 'green',
    title: 'To Make More Wind',
    text: 'There was no wind, so {name} ran. Up and down the Green, the kite bumping along behind like a reluctant dog. {other} eventually joined in, “to make more wind.” It didn’t work. It was the best afternoon of the week.',
    mark: 'grassStain',
    tags: ['kite', 'play'],
  },
  {
    id: 'kite_rain',
    object: 'kite',
    weather: ['rainy'],
    priority: 44,
    location: 'green',
    title: 'The Kite Declined',
    text: '{name} tried to fly the kite in the rain. The kite declined. They sat under the bandstand together, the kite and {name}, and watched it pour.',
    mark: 'mudSplash',
    tags: ['kite'],
  },
  {
    id: 'kite_social',
    chance: 0.5,
    object: 'kite',
    weather: ['windy'],
    other: { kind: 'any' },
    priority: 24,
    title: 'A Bit More String',
    text: '{name} and {other} took turns with the kite on Observatory Hill until it was a red dot against the clouds. It pulled like it wanted to go somewhere. They let it have a bit more string.',
    mark: 'knot',
    tags: ['kite'],
  },
  {
    id: 'kite_solo',
    object: 'kite',
    priority: 10,
    title: 'As Long as the Air Allowed',
    text: '{name} took the kite up Observatory Hill and flew it for as long as the air would allow. It pulled like it wanted to go somewhere.',
    mark: 'knot',
    tags: ['kite'],
  },
]

const boardGame: EchoDef[] = [
  {
    id: 'game_rematch',
    object: 'boardGame',
    other: { kind: 'trace', keepsakeOnly: true },
    priority: 79,
    title: 'The Rematch',
    text: 'The score sheet in the lid said, in {other}’s writing: “{keepsake}” This could not be allowed to stand. {name} challenged {other} to a rematch. The sheet now has a new column, and a small tea ring.',
    keepsake: { text: '{NAME} 1 · {OTHER} 0 (rematch — {OTHER} disputes this)' },
    mark: 'teaRing',
    tags: ['games'],
  },
  {
    id: 'game_tobias_barnaby',
    object: 'boardGame',
    resident: 'tobias',
    other: { kind: 'resident', id: 'barnaby' },
    priority: 72,
    once: true,
    title: 'One Quick Game',
    text: 'Tobias invited Barnaby round for “one quick game.” They played until midnight. The score sheet now reads TOBIAS 4, BARNABY 4, and a disputed note: “his snail touched the ladder, it counts.” It does not count.',
    keepsake: true,
    mark: 'teaRing',
    tags: ['games'],
  },
  {
    id: 'game_barnaby_tobias',
    object: 'boardGame',
    resident: 'barnaby',
    other: { kind: 'resident', id: 'tobias' },
    priority: 70,
    once: true,
    location: 'kettleRow',
    title: 'Can Snails Go Backwards?',
    text: 'Barnaby turned up at Tobias’s door with the board game and a loaf. They argued for four hours about whether snails can go backwards. The score sheet says BARNABY 3, TOBIAS 5, and underneath, in capitals: RECOUNT.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['games'],
  },
  {
    id: 'game_hollis',
    object: 'boardGame',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 68,
    once: true,
    title: 'Won by Accident',
    text: 'Hollis and {other} played Snails & Ladders at his kitchen table. Hollis won three times by accident and apologised each time. {other} has demanded a fourth game, as a matter of honour.',
    keepsake: { text: 'HOLLIS 3 (sorry) · {OTHER} 0' },
    mark: 'button',
    tags: ['games', 'host'],
  },
  {
    id: 'game_tansy',
    object: 'boardGame',
    resident: 'tansy',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'When the Rules Settle Down',
    text: 'Tansy taught {other} Snails & Ladders using rules she invented halfway through. {other} lost magnificently and has asked for a rematch “when the rules settle down.”',
    keepsake: true,
    mark: 'doodle',
    tags: ['games'],
  },
  {
    id: 'game_odile',
    object: 'boardGame',
    resident: 'odile',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'Suspiciously Gracious',
    text: 'Odile played Snails & Ladders with {other} by the fire, very seriously. She lost, and was so gracious about it that {other} suspects a trap.',
    keepsake: { text: '{OTHER} 1 · ODILE 0 (for now)' },
    mark: 'teaRing',
    tags: ['games'],
  },
  {
    id: 'game_margo',
    object: 'boardGame',
    resident: 'margo',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'A Strategy',
    text: 'Margo played {other} and cheated openly, which she says is “a strategy.” {other} started cheating back. It is now a completely different game, and they both love it.',
    keepsake: true,
    mark: 'scratch',
    tags: ['games'],
  },
  {
    id: 'game_rain',
    object: 'boardGame',
    weather: ['rainy'],
    other: { kind: 'any' },
    priority: 42,
    title: 'Until the Rain Gave Up',
    text: 'Rain on the windows, snails on the ladders. {name} and {other} played until the rain gave up first.',
    keepsake: { text: '{NAME} 2 · {OTHER} 2 · RAIN 0' },
    mark: 'teaRing',
    tags: ['games'],
  },
  {
    id: 'game_social',
    chance: 0.5,
    object: 'boardGame',
    other: { kind: 'any' },
    priority: 22,
    title: 'Best of Five',
    text: '{name} set up Snails & Ladders and {other} happened by at exactly the right moment. They played best of three, then best of five, then stopped counting.',
    keepsake: { text: '{NAME} vs {OTHER}: stopped counting' },
    mark: 'teaRing',
    tags: ['games'],
  },
  {
    id: 'game_solo',
    object: 'boardGame',
    priority: 10,
    title: 'Both Sides',
    text: '{name} played both sides of Snails & Ladders and somehow lost twice.',
    mark: 'scratch',
    tags: ['games'],
  },
]

const thermos: EchoDef[] = [
  {
    id: 'thermos_barnaby_odile',
    object: 'thermos',
    resident: 'barnaby',
    requestTags: ['courage'],
    other: { kind: 'resident', id: 'odile' },
    priority: 76,
    once: true,
    location: 'green',
    title: 'Cocoa, Instead of Morning',
    text: 'Barnaby filled the thermos with his best cocoa and waited by the post box at nine. When Odile arrived, he said “cocoa?” instead of “morning.” It was, historically speaking, a breakthrough.',
    mark: 'teaRing',
    tags: ['tea', 'courage'],
  },
  {
    id: 'thermos_odile_fog',
    object: 'thermos',
    resident: 'odile',
    weather: ['foggy', 'rainy'],
    other: { kind: 'resident', id: 'tobias' },
    priority: 72,
    once: true,
    location: 'kettleRow',
    title: 'Twelve Minutes',
    text: 'Odile did the round with the thermos in her satchel and offered a cup at every door. At the ninth door, Tobias asked her in. She stayed twelve minutes, which in postal terms is a holiday.',
    mark: 'teaRing',
    tags: ['tea'],
  },
  {
    id: 'thermos_hollis',
    object: 'thermos',
    resident: 'hollis',
    weather: ['rainy', 'foggy'],
    other: { kind: 'any' },
    priority: 64,
    once: true,
    location: 'green',
    title: 'Cups for Anyone Hurrying',
    text: 'Hollis stood happily out in the weather with the thermos, offering cups to anyone who hurried past. {other} stopped. Then stayed. Then went home and fetched a second cup.',
    mark: 'teaRing',
    tags: ['tea'],
  },
  {
    id: 'thermos_tobias',
    object: 'thermos',
    resident: 'tobias',
    weather: ['foggy'],
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'Listening to the Fog',
    text: 'Tobias sat on the bench by the Millpond with the thermos and listened to the fog. {other} sat down beside him without seeing him, and jumped a foot. They shared the tea anyway.',
    mark: 'teaRing',
    tags: ['tea'],
  },
  {
    id: 'thermos_margo',
    object: 'thermos',
    resident: 'margo',
    closed: 'glasshouse',
    other: { kind: 'any' },
    priority: 60,
    once: true,
    location: 'glasshouse',
    title: 'Glaring in Solidarity',
    text: 'Margo took the thermos to the Glasshouse, sat on an upturned bucket and glared at the jammed door. {other} brought biscuits and glared too, in solidarity.',
    mark: 'teaRing',
    tags: ['tea'],
  },
  {
    id: 'thermos_tansy',
    object: 'thermos',
    resident: 'tansy',
    priority: 58,
    once: true,
    title: 'Expedition Rations',
    text: 'Tansy took the thermos on an expedition to the far side of the Millpond, which is about four minutes away. She rationed the cocoa carefully and drank all of it in the first minute.',
    mark: 'mudSplash',
    tags: ['tea'],
  },
  {
    id: 'thermos_fog',
    object: 'thermos',
    weather: ['foggy'],
    other: { kind: 'any' },
    priority: 42,
    title: 'A Shape in the Fog',
    text: '{name} walked into the fog with the thermos, and the fog walked back. At the Millpond, a shape slowly became {other}. Tea was the obvious thing.',
    mark: 'teaRing',
    tags: ['tea'],
  },
  {
    id: 'thermos_social',
    chance: 0.5,
    object: 'thermos',
    other: { kind: 'any' },
    priority: 22,
    title: 'Two Cups, Out of Habit',
    text: '{name} took the thermos down to the Millpond and poured two cups out of habit. {other} happened by and made it make sense.',
    mark: 'teaRing',
    tags: ['tea'],
  },
  {
    id: 'thermos_solo',
    object: 'thermos',
    priority: 10,
    title: 'Still Hot',
    text: '{name} sat by the Millpond with the thermos and watched the ducks being busy. The tea was still hot when {they} got home.',
    mark: 'teaRing',
    tags: ['tea'],
  },
]

const lantern: EchoDef[] = [
  {
    id: 'lantern_tobias',
    object: 'lantern',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 70,
    once: true,
    location: 'hill',
    title: 'The Rest of the Way',
    text: 'Tobias walked up the Hill with the lantern, slowly, the way he and Hettie used to. Halfway up he met {other} coming down, who turned round without a word and walked him the rest of the way.',
    mark: 'waxDrip',
    tags: ['night', 'memory'],
  },
  {
    id: 'lantern_tansy_dark',
    object: 'lantern',
    resident: 'tansy',
    notFlags: ['tansy_brave'],
    priority: 70,
    once: true,
    title: 'So the Dark Knew She Was Coming',
    text: 'Tansy walked to the end of Kettle Row in the dark with the lantern held very high. Then to the Green. Then — singing loudly, so the dark knew she was coming — right to the bottom of the Hill. She came home with mud on the lantern and her chin up.',
    mark: 'mudSplash',
    tags: ['night', 'brave'],
    flagsSet: ['tansy_brave'],
  },
  {
    id: 'lantern_tansy_hill',
    object: 'lantern',
    resident: 'tansy',
    flags: ['tansy_brave'],
    clearNight: true,
    priority: 68,
    once: true,
    location: 'hill',
    title: 'Forty Stars',
    text: 'Tansy took the lantern straight up the Hill this time. She stayed until she had counted forty stars, then came down very pleased with herself, and only slightly running.',
    mark: 'starSticker',
    tags: ['night', 'stargazing'],
    flagsSet: ['tansy_stargazed'],
  },
  {
    id: 'lantern_odile',
    object: 'lantern',
    resident: 'odile',
    weather: ['foggy', 'rainy'],
    other: { kind: 'any' },
    priority: 66,
    once: true,
    location: 'green',
    time: 'dusk',
    title: 'A Lighthouse on Legs',
    text: 'Odile walked the lanes in the murk with the lantern held high, like a lighthouse on legs. Three people followed her home by accident, including {other}, who stayed for toast.',
    mark: 'waxDrip',
    tags: ['night'],
  },
  {
    id: 'lantern_hollis',
    object: 'lantern',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    title: 'Not for Himself',
    text: 'Hollis carried the lantern around Mosswick after dark — not for himself; he sees about the same either way — but so that {other}, walking home late, could find the path. They got talking about maps.',
    mark: 'waxDrip',
    tags: ['night'],
  },
  {
    id: 'lantern_margo',
    object: 'lantern',
    resident: 'margo',
    other: { kind: 'any' },
    priority: 60,
    once: true,
    location: 'glasshouse',
    title: 'Eleven Slugs and a Neighbour',
    text: 'Margo took the lantern out to check for slugs. She found eleven slugs and {other}, who was lost. Both were escorted firmly off the premises. Only one was invited back for tea.',
    mark: 'waxDrip',
    tags: ['night'],
  },
  {
    id: 'lantern_barnaby',
    object: 'lantern',
    resident: 'barnaby',
    priority: 58,
    once: true,
    location: 'green',
    title: 'The Long Way Round',
    text: 'Barnaby lit the lantern at four in the morning and walked to the bakery by it, instead of by memory. Everything looked new. He took the long way, past the post office. Twice.',
    mark: 'waxDrip',
    tags: ['night'],
  },
  {
    id: 'lantern_social',
    chance: 0.5,
    object: 'lantern',
    other: { kind: 'any' },
    priority: 22,
    time: 'dusk',
    title: 'Four Moths and a Frog',
    text: '{name} took the lantern out at dusk and collected, in order: four moths, a startled frog, and {other}, who was on the way home and glad of the light.',
    mark: 'waxDrip',
    tags: ['night'],
  },
  {
    id: 'lantern_solo',
    object: 'lantern',
    priority: 10,
    title: 'Somewhere New',
    text: '{name} walked around Mosswick with the lantern after dark. Everything familiar looked like somewhere new.',
    mark: 'waxDrip',
    tags: ['night'],
  },
]

const umbrella: EchoDef[] = [
  {
    id: 'umb_hollis',
    object: 'umbrella',
    resident: 'hollis',
    weather: ['rainy'],
    other: { kind: 'any' },
    priority: 68,
    once: true,
    title: 'Everybody’s Footsteps',
    text: 'Hollis walked slowly round the village in the rain, holding the umbrella over anyone who looked like they needed it. He met four people and learned all their footsteps. {other} walked with him the whole last lap.',
    mark: 'mudSplash',
    tags: ['rain'],
  },
  {
    id: 'umb_barnaby',
    object: 'umbrella',
    resident: 'barnaby',
    weather: ['rainy'],
    other: { kind: 'resident', id: 'odile' },
    priority: 66,
    once: true,
    title: 'Exactly Big Enough',
    text: 'Barnaby “happened” to be crossing the Green with the big green umbrella at nine o’clock exactly, just as Odile was doing the round. He walked her to every door. They discussed the weather thoroughly. Neither of them minded.',
    mark: 'mudSplash',
    tags: ['rain'],
  },
  {
    id: 'umb_tansy',
    object: 'umbrella',
    resident: 'tansy',
    priority: 62,
    once: true,
    location: 'kettleRow',
    title: 'Boat, Tent, Umbrella',
    text: 'Tansy used the umbrella as a boat in the big puddle on Kettle Row, then as a tent, then — briefly, in a gust — as an actual umbrella.',
    mark: 'mudSplash',
    tags: ['play'],
  },
  {
    id: 'umb_odile',
    object: 'umbrella',
    resident: 'odile',
    weather: ['rainy'],
    priority: 62,
    once: true,
    title: 'Dry, for Once',
    text: 'Odile did the whole round under the big green umbrella and arrived at the last door completely dry for the first time in twenty years. She stood there for a while, unsure how to feel about it.',
    mark: 'label',
    markNote: 'O.F. — dry!',
    tags: ['rain'],
  },
  {
    id: 'umb_tobias',
    object: 'umbrella',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'The Bandstand Used to Be There',
    text: 'Tobias used the umbrella partly as a walking stick and partly as a pointer, to show {other} where the bandstand used to be. “Bandstands don’t move,” said {other}. “This one did,” said Tobias. It is a long story. {other} heard all of it.',
    mark: 'scratch',
    tags: ['walk', 'memory'],
  },
  {
    id: 'umb_margo',
    object: 'umbrella',
    resident: 'margo',
    weather: ['rainy'],
    priority: 60,
    once: true,
    location: 'glasshouse',
    title: 'Keeping the Rain Off the Rain',
    text: 'Margo held the umbrella over her seedlings for an hour, to stop the rain being too rough with them. The seedlings are fine. Margo is soaked. She considers this correct.',
    mark: 'mudSplash',
    tags: ['rain', 'garden'],
  },
  {
    id: 'umb_share',
    object: 'umbrella',
    weather: ['rainy'],
    other: { kind: 'any' },
    priority: 44,
    title: 'Fond Quite Quickly',
    text: '{name} walked across the Green under the big green umbrella and found {other} sheltering in the bakery doorway. The umbrella is exactly big enough for two, if both parties are fond of each other. They got fond quite quickly.',
    mark: 'mudSplash',
    tags: ['rain'],
  },
  {
    id: 'umb_wind',
    object: 'umbrella',
    weather: ['windy'],
    other: { kind: 'any' },
    priority: 44,
    title: 'Inside Out',
    text: 'The wind turned the umbrella inside out in the middle of the Green. {other} helped turn it the right way round. It now has a kink in one spoke and a friendship attached.',
    mark: 'dent',
    tags: ['wind'],
  },
  {
    id: 'umb_sun',
    object: 'umbrella',
    weather: ['sunny'],
    other: { kind: 'any' },
    priority: 36,
    title: 'Tremendously Distinguished',
    text: '{name} used the umbrella as a parasol and looked tremendously distinguished doing it. {other} said so. {name} has decided to believe {other}.',
    mark: 'label',
    markNote: 'parasol (occasionally)',
    tags: ['walk'],
  },
  {
    id: 'umb_solo',
    object: 'umbrella',
    priority: 10,
    title: 'Just in Case',
    text: '{name} took the big green umbrella for a walk, just in case. It rained a bit, then didn’t, then did. The umbrella handled all of it.',
    mark: 'mudSplash',
    tags: ['walk'],
  },
]

const paints: EchoDef[] = [
  {
    id: 'paint_odile_finds',
    object: 'paints',
    resident: 'odile',
    flags: ['barnaby_painted_odile'],
    other: { kind: 'trace', by: 'barnaby', keepsakeOnly: true },
    priority: 88,
    once: true,
    location: 'green',
    title: 'A Small Striped Figure',
    text: 'In the sketchbook, Odile found the post office, painted with great care, and a small grey figure in the doorway who could only be her. On the next page she painted the bakery, with a small striped figure in the window. She has not explained this to anybody.',
    keepsake: { text: 'the bakery, with a small striped figure in the window', subject: 'barnaby' },
    mark: 'paintDab',
    tags: ['painting'],
    flagsSet: ['odile_painted'],
  },
  {
    id: 'paint_barnaby',
    object: 'paints',
    resident: 'barnaby',
    priority: 64,
    once: true,
    location: 'green',
    title: 'The Smallest Brush',
    text: 'Barnaby painted a loaf of bread, then the bakery, then — carefully, with the smallest brush — the post office, with a small grey figure in its doorway.',
    keepsake: true,
    mark: 'paintDab',
    tags: ['painting'],
    flagsSet: ['barnaby_painted_odile'],
  },
  {
    id: 'paint_tansy',
    object: 'paints',
    resident: 'tansy',
    other: { kind: 'resident', id: 'tobias' },
    priority: 64,
    once: true,
    location: 'kettleRow',
    title: 'Tobias, as the Moon',
    text: 'Tansy painted the Moon, then the Moon again, and then a portrait of Tobias as the Moon. She gave it to him. He put it on his mantelpiece, next to the clock, and keeps looking at it.',
    keepsake: true,
    mark: 'paintDab',
    tags: ['painting', 'moon'],
  },
  {
    id: 'paint_odile',
    object: 'paints',
    resident: 'odile',
    notFlags: ['odile_painted'],
    other: { kind: 'resident', id: 'hollis' },
    priority: 64,
    once: true,
    location: 'green',
    title: 'Every Door Numbered',
    text: 'Odile painted Mosswick from memory, every door correct and numbered. It is the most accurate painting ever made, and she is worried it is boring. Hollis saw it and asked, very politely, if he could copy it for his map.',
    keepsake: true,
    mark: 'paintDab',
    tags: ['painting', 'map'],
    flagsSet: ['odile_painted'],
  },
  {
    id: 'paint_hollis',
    object: 'paints',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    location: 'kettleRow',
    title: 'Drawn as Footsteps',
    text: 'Hollis painted a watercolour map of Kettle Row with everybody drawn as their footsteps. {other} found their own straight away and was absurdly pleased.',
    keepsake: true,
    mark: 'paintDab',
    tags: ['painting', 'map'],
  },
  {
    id: 'paint_tobias',
    object: 'paints',
    resident: 'tobias',
    priority: 64,
    once: true,
    location: 'kettleRow',
    title: 'Hettie at the Gate',
    text: 'Tobias painted Kettle Row as it was in 1952 — the lamppost, the horse trough, Hettie at the gate. His hand shook a little. It doesn’t matter at all.',
    keepsake: true,
    mark: 'paintDab',
    tags: ['painting', 'memory'],
  },
  {
    id: 'paint_margo_open',
    object: 'paints',
    resident: 'margo',
    open: 'glasshouse',
    priority: 62,
    once: true,
    location: 'glasshouse',
    title: 'Fourteen Squash, One Door',
    text: 'Margo painted squash. Fourteen squash. The fifteenth painting is the Glasshouse with its door flung wide open, which — at long last — it is.',
    keepsake: { text: 'fourteen squash, and the Glasshouse, door open at last' },
    mark: 'paintDab',
    tags: ['painting'],
    flagsSet: ['margo_poem'],
  },
  {
    id: 'paint_margo',
    object: 'paints',
    resident: 'margo',
    closed: 'glasshouse',
    priority: 62,
    once: true,
    location: 'glasshouse',
    title: 'Fourteen Squash',
    text: 'Margo painted squash. Fourteen squash. The fifteenth painting is the Glasshouse with its door flung wide open — which it isn’t. Not yet.',
    keepsake: true,
    mark: 'paintDab',
    tags: ['painting'],
  },
  {
    id: 'paint_odile_solo',
    object: 'paints',
    resident: 'odile',
    notFlags: ['odile_painted'],
    priority: 56,
    once: true,
    location: 'green',
    title: 'Every Door Numbered',
    text: 'Odile painted Mosswick from memory, every door correct and numbered. It is the most accurate painting ever made, and she is worried it is boring. It is not.',
    keepsake: true,
    mark: 'paintDab',
    tags: ['painting'],
    flagsSet: ['odile_painted'],
  },
  {
    id: 'paint_rain',
    object: 'paints',
    weather: ['rainy'],
    other: { kind: 'any' },
    priority: 42,
    location: 'home',
    indoor: true,
    title: 'Dripping on the Mat',
    text: '{name} painted the rain from a window seat and ended up with a lovely grey painting and a cup of tea gone cold. {other} came in out of the wet and was drafted as a model.',
    keepsake: { text: 'the rain, and {other} dripping on the mat', subject: 'other' },
    mark: 'paintDab',
    tags: ['painting'],
  },
  {
    id: 'paint_social',
    chance: 0.5,
    object: 'paints',
    other: { kind: 'any' },
    priority: 22,
    title: 'A Second Brush',
    text: '{name} set up by the Millpond with the watercolours. {other} came to look over {their} shoulder, then fetched a chair, then a second brush.',
    keepsake: { text: 'the Millpond in the afternoon, painted by two people' },
    mark: 'paintDab',
    tags: ['painting'],
  },
  {
    id: 'paint_solo',
    object: 'paints',
    priority: 10,
    title: 'Better Than Expected',
    text: '{name} painted {place} all afternoon, and it came out better than {they} expected, which is the best kind of painting.',
    keepsake: { text: '{place}, in watercolour' },
    mark: 'paintDab',
    tags: ['painting'],
  },
]

const gardenKit: EchoDef[] = [
  {
    id: 'garden_tansy',
    object: 'gardenKit',
    resident: 'tansy',
    priority: 70,
    once: true,
    location: 'green',
    title: 'Something Tall to Talk To',
    text: 'Tansy planted an entire packet of sunflower seeds along the post office wall, “so Odile has something tall to talk to.”',
    keepsake: true,
    mark: 'mudSplash',
    tags: ['garden'],
    flagsSet: ['sunflowers_planted'],
    schedule: { inDays: 3, id: 'bloom_sunflowers' },
  },
  {
    id: 'garden_hollis',
    object: 'gardenKit',
    resident: 'hollis',
    other: { kind: 'any', prefer: ['margo'] },
    priority: 68,
    once: true,
    location: 'kettleRow',
    title: 'Gifted Diggers',
    text: 'Hollis dug a flower bed beside his front step — exceptionally well; moles are gifted diggers — and planted bulbs. {other} leaned on the gate to watch, ended up giving advice, and then a hand.',
    keepsake: true,
    mark: 'mudSplash',
    tags: ['garden'],
    flagsSet: ['bulbs_planted'],
    schedule: { inDays: 2, id: 'bloom_bulbs' },
  },
  {
    id: 'garden_margo_open',
    object: 'gardenKit',
    resident: 'margo',
    open: 'glasshouse',
    other: { kind: 'any' },
    priority: 68,
    once: true,
    location: 'glasshouse',
    title: 'The Highest Honour',
    text: 'Margo planted out the whole back bed of the reopened Glasshouse and allowed {other} to help, which is the highest honour Margo can bestow.',
    keepsake: { text: 'THE BACK BED — Glasshouse — (with help)' },
    mark: 'mudSplash',
    tags: ['garden'],
  },
  {
    id: 'garden_barnaby',
    object: 'gardenKit',
    resident: 'barnaby',
    priority: 64,
    once: true,
    location: 'green',
    title: 'A Window Box of Herbs',
    text: 'Barnaby planted rosemary, thyme and something Margo swears is basil in a window box behind the bakery. He is already planning the loaf.',
    keepsake: true,
    mark: 'mudSplash',
    tags: ['garden'],
    flagsSet: ['herbs_planted'],
    schedule: { inDays: 2, id: 'bloom_herbs' },
  },
  {
    id: 'garden_tobias',
    object: 'gardenKit',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    location: 'kettleRow',
    title: 'Sweet Peas, as Always',
    text: 'Tobias planted sweet peas up his front railings, the way he and Hettie did every year. It took all afternoon. {other} held the string.',
    keepsake: true,
    mark: 'mudSplash',
    tags: ['garden', 'memory'],
    flagsSet: ['sweetpeas_planted'],
    schedule: { inDays: 2, id: 'bloom_sweetpeas' },
  },
  {
    id: 'garden_margo_closed',
    object: 'gardenKit',
    resident: 'margo',
    closed: 'glasshouse',
    priority: 62,
    once: true,
    location: 'glasshouse',
    title: 'The Gravy Boat',
    text: 'Margo potted up forty seedlings on her doorstep, muttering about the Glasshouse door. She has run out of teapots and started on the gravy boat.',
    keepsake: true,
    mark: 'mudSplash',
    tags: ['garden'],
  },
  {
    id: 'garden_odile',
    object: 'gardenKit',
    resident: 'odile',
    priority: 60,
    once: true,
    location: 'green',
    title: 'Measured With a Ruler',
    text: 'Odile planted lavender in a perfectly straight line by the post box. She measured it. With a ruler. Twice.',
    keepsake: true,
    mark: 'mudSplash',
    tags: ['garden'],
    flagsSet: ['lavender_planted'],
    schedule: { inDays: 2, id: 'bloom_lavender' },
  },
  {
    id: 'garden_rain',
    object: 'gardenKit',
    weather: ['rainy'],
    other: { kind: 'any' },
    priority: 42,
    title: 'A Second Trowel',
    text: '{name} planted bulbs in the rain, which the bulbs seemed to appreciate. {other} came out with a second trowel and a hat.',
    keepsake: { text: 'BULBS — planted in the rain — with {other}' },
    mark: 'mudSplash',
    tags: ['garden'],
  },
  {
    id: 'garden_social',
    chance: 0.5,
    object: 'gardenKit',
    other: { kind: 'any' },
    priority: 22,
    title: 'Nothing Important',
    text: '{name} spent the afternoon weeding the verge by the Green. {other} stopped to help, and they cleared the whole thing, talking about nothing important.',
    mark: 'mudSplash',
    tags: ['garden'],
  },
  {
    id: 'garden_solo',
    object: 'gardenKit',
    priority: 10,
    title: 'Something Will Come Up',
    text: '{name} dug, planted, watered and stood back. Something will come up. Probably.',
    keepsake: { text: 'SOMETHING — probably' },
    mark: 'mudSplash',
    tags: ['garden'],
  },
]

const toolbox: EchoDef[] = [
  {
    id: 'tool_tobias_glass',
    object: 'toolbox',
    resident: 'tobias',
    closed: 'glasshouse',
    other: { kind: 'resident', id: 'margo' },
    priority: 92,
    once: true,
    location: 'glasshouse',
    title: 'The Door That Wouldn’t',
    text: 'Tobias walked to the Glasshouse with the toolbox, oiled every hinge, reset the door on its pins and had it swinging within the hour. Margo made him tea, called him “a genius,” and immediately denied it.',
    mark: 'scratch',
    tags: ['repair', 'glasshouse'],
    flagsSet: ['glasshouse_open'],
  },
  {
    id: 'tool_hollis_glass',
    object: 'toolbox',
    resident: 'hollis',
    closed: 'glasshouse',
    other: { kind: 'resident', id: 'margo' },
    priority: 92,
    once: true,
    location: 'glasshouse',
    title: 'Under, Not Through',
    text: 'Hollis tried to fix the Glasshouse door with the toolbox, failed politely, and then — being a mole — simply dug under it. Margo found him inside among the tomatoes, covered in soil and apologising. She laughed so hard she had to sit down. Then they fixed the door together.',
    mark: 'mudSplash',
    tags: ['repair', 'glasshouse'],
    flagsSet: ['glasshouse_open'],
  },
  {
    id: 'tool_margo_glass',
    object: 'toolbox',
    resident: 'margo',
    closed: 'glasshouse',
    priority: 90,
    once: true,
    location: 'glasshouse',
    title: 'Considerable Language',
    text: 'Margo took the toolbox to the Glasshouse and fixed the jammed door with a wrench, a hammer and considerable language. It swung open with a sigh that everyone on the Green heard.',
    mark: 'dent',
    tags: ['repair', 'glasshouse'],
    flagsSet: ['glasshouse_open'],
  },
  {
    id: 'tool_tobias_glass_note',
    object: 'toolbox',
    resident: 'tobias',
    closed: 'glasshouse',
    priority: 90,
    once: true,
    location: 'glasshouse',
    title: 'Hinges. — T.C.',
    text: 'Tobias walked to the Glasshouse while Margo was out, oiled every hinge and reset the door on its pins. She came home to find it swinging gently, and a note in careful handwriting: “Hinges. — T.C.”',
    mark: 'scratch',
    tags: ['repair', 'glasshouse'],
    flagsSet: ['glasshouse_open'],
  },
  {
    id: 'tool_hollis_glass_solo',
    object: 'toolbox',
    resident: 'hollis',
    closed: 'glasshouse',
    priority: 90,
    once: true,
    location: 'glasshouse',
    title: 'Under, Not Through',
    text: 'Hollis tried to fix the Glasshouse door with the toolbox, failed politely, and then — being a mole — dug under it and fixed it from the inside. Margo came home to an open door, a very neat tunnel, and a note that said “Sorry.”',
    mark: 'mudSplash',
    tags: ['repair', 'glasshouse'],
    flagsSet: ['glasshouse_open'],
  },
  {
    id: 'tool_tansy',
    object: 'toolbox',
    resident: 'tansy',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    location: 'kettleRow',
    indoor: false,
    title: 'The Rocket',
    text: 'Tansy built a rocket from a crate, two saucepans and most of the toolbox. It did not reach the Moon. It did reach the bottom of Kettle Row, quite quickly. {other} caught her.',
    mark: 'dent',
    tags: ['repair', 'play', 'moon'],
  },
  {
    id: 'tool_tobias',
    object: 'toolbox',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    title: 'A Music Box From 1971',
    text: 'Word got round, and Tobias spent the afternoon fixing things people brought him: {other}’s clock, a squeaky pram, and a music box that hadn’t played since 1971. It plays now.',
    mark: 'scratch',
    tags: ['repair'],
  },
  {
    id: 'tool_odile',
    object: 'toolbox',
    resident: 'odile',
    priority: 62,
    once: true,
    location: 'green',
    indoor: false,
    title: 'The Bench Faces the Sunset',
    text: 'Odile fixed the post box flap, a gate latch and a wobbly bench on the Green. She did not mention it to anyone. The bench now faces the sunset.',
    mark: 'label',
    markNote: 'bench: fixed. — O.F.',
    tags: ['repair'],
    flagsSet: ['bench_fixed'],
  },
  {
    id: 'tool_hollis',
    object: 'toolbox',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 60,
    once: true,
    location: 'kettleRow',
    indoor: false,
    title: 'A Signpost',
    text: 'Hollis built a little signpost at the end of Kettle Row pointing to everything: THE GREEN, THE HILL, THE MILLPOND, HOME. {other} asked him to add their house. He added everyone’s.',
    mark: 'scratch',
    tags: ['repair', 'map'],
    flagsSet: ['signpost'],
  },
  {
    id: 'tool_barnaby',
    object: 'toolbox',
    resident: 'barnaby',
    priority: 60,
    once: true,
    title: 'Four Minutes Late',
    text: 'Barnaby fixed the bakery clock, which has run four minutes fast since 1994. He is now four minutes late for everything and has never been happier.',
    mark: 'flourPrint',
    tags: ['repair'],
  },
  {
    id: 'tool_margo',
    object: 'toolbox',
    resident: 'margo',
    open: 'glasshouse',
    priority: 60,
    once: true,
    location: 'glasshouse',
    title: 'Measure Twice, Cut Angrily',
    text: 'Margo built new potting benches for the Glasshouse. She measured twice, cut once, and then cut again, angrily. They are very good benches.',
    mark: 'scratch',
    tags: ['repair'],
  },
  {
    id: 'tool_social',
    chance: 0.5,
    object: 'toolbox',
    other: { kind: 'any' },
    priority: 22,
    title: 'A Wobbly Chair',
    text: '{name} spent the afternoon fixing things around the house. {other} heard the hammering and came round with a wobbly chair of their own.',
    mark: 'scratch',
    tags: ['repair'],
  },
  {
    id: 'tool_solo',
    object: 'toolbox',
    priority: 10,
    title: 'Never Actually Broken',
    text: '{name} fixed a drawer, a hinge and a thing that was never actually broken. Very satisfying.',
    mark: 'scratch',
    tags: ['repair'],
  },
]

const birdGuide: EchoDef[] = [
  {
    id: 'bird_kingfisher',
    object: 'birdGuide',
    notResident: ['tobias'],
    other: { kind: 'trace', by: 'tobias', keepsakeOnly: true },
    priority: 84,
    once: true,
    title: 'Early, by the Jetty',
    text: 'In the margin, in Tobias’s pencil: “Kingfisher by the jetty, early. Worth the cold.” So {name} went at dawn, and found Tobias already there on the bench, as if he had been waiting to see who would come. The kingfisher came too.',
    keepsake: true,
    mark: 'feather',
    tags: ['birds'],
  },
  {
    id: 'bird_hollis',
    object: 'birdGuide',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 66,
    once: true,
    title: 'Fourteen by Song',
    text: 'Hollis identified fourteen birds by song alone and two by sight. {other} was so impressed that they went through the whole guide together afterwards, {other} reading out the pictures.',
    keepsake: true,
    mark: 'feather',
    tags: ['birds'],
  },
  {
    id: 'bird_tobias',
    object: 'birdGuide',
    resident: 'tobias',
    priority: 64,
    once: true,
    title: 'Worth the Cold',
    text: 'Tobias took the guide down to the jetty at dawn and waited, very still, for an hour. Being a tortoise, he is excellent at very still. He saw the kingfisher, and pencilled a note for whoever borrows the guide next.',
    keepsake: true,
    mark: 'feather',
    tags: ['birds'],
    flagsSet: ['kingfisher_tip'],
  },
  {
    id: 'bird_odile',
    object: 'birdGuide',
    resident: 'odile',
    priority: 62,
    once: true,
    title: 'Page 41',
    text: 'Odile borrowed back her own bird guide, which she says is “not the same thing at all,” and ticked off eleven species at the Millpond — including, on page 41, herself.',
    keepsake: true,
    mark: 'feather',
    tags: ['birds'],
  },
  {
    id: 'bird_tansy',
    object: 'birdGuide',
    resident: 'tansy',
    priority: 62,
    once: true,
    title: 'Or Is It',
    text: 'Tansy used the bird guide to identify the thing under the jetty. It is a moorhen. She remains unconvinced, and has written “OR IS IT” in the margin.',
    keepsake: true,
    mark: 'doodle',
    tags: ['birds'],
  },
  {
    id: 'bird_margo',
    object: 'birdGuide',
    resident: 'margo',
    priority: 60,
    once: true,
    title: 'ENEMIES',
    text: 'Margo used the bird guide to identify which birds have been eating her peas, and copied their names into a notebook titled ENEMIES.',
    keepsake: true,
    mark: 'feather',
    tags: ['birds'],
  },
  {
    id: 'bird_barnaby',
    object: 'birdGuide',
    resident: 'barnaby',
    priority: 60,
    once: true,
    location: 'green',
    title: 'A Robin Named Crumb',
    text: 'Barnaby looked up the bird that sits on the bakery step every morning. It is a robin. He has named it anyway, and now puts out crumbs on a saucer, which the robin considers only fair.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['birds'],
  },
  {
    id: 'bird_social',
    chance: 0.5,
    object: 'birdGuide',
    other: { kind: 'any' },
    priority: 22,
    title: 'Staring Together',
    text: '{name} took the bird guide to the Millpond and ticked off a moorhen, a coot and a very small grebe. {other} came to see what {name} was staring at, and stayed to stare too.',
    mark: 'feather',
    tags: ['birds'],
  },
  {
    id: 'bird_solo',
    object: 'birdGuide',
    priority: 10,
    title: 'Counted Back',
    text: '{name} sat very still by the Millpond with the bird guide and counted nine kinds of bird. The ducks counted {them} back.',
    mark: 'feather',
    tags: ['birds'],
  },
]

const binoculars: EchoDef[] = [
  {
    id: 'bino_jupiter',
    object: 'binoculars',
    resident: 'tansy',
    requestTags: ['sky', 'night'],
    clearNight: true,
    priority: 70,
    once: true,
    location: 'hill',
    time: 'night',
    title: 'Four Tiny Moons',
    text: 'Tansy found her bright dot with the binoculars. It was Jupiter, with four tiny moons lined up beside it like ducklings. She was, she says, “completely right, about everything, always.”',
    mark: 'starSticker',
    tags: ['stargazing'],
    flagsSet: ['tansy_stargazed', 'jupiter'],
  },
  {
    id: 'bino_margo',
    object: 'binoculars',
    resident: 'margo',
    other: { kind: 'resident', id: 'barnaby' },
    priority: 70,
    once: true,
    location: 'green',
    title: 'Surveillance',
    text: 'Margo used the binoculars to keep an eye on Barnaby’s marrow from a safe distance. Barnaby, it turned out, was keeping an eye on hers. They met in the middle of the Green to complain about each other and stayed for an hour.',
    mark: 'grassStain',
    tags: ['marrow'],
  },
  {
    id: 'bino_odile',
    object: 'binoculars',
    resident: 'odile',
    priority: 64,
    once: true,
    location: 'millpond',
    title: 'Four O’Clock Came and Went',
    text: 'Odile watched a kingfisher at the Millpond for an hour and missed four o’clock tea for the first time in eleven years. She says she doesn’t regret it, in a way that suggests she is still thinking about it.',
    mark: 'feather',
    tags: ['birds'],
    flagsSet: ['odile_rested'],
  },
  {
    id: 'bino_tansy',
    object: 'binoculars',
    resident: 'tansy',
    priority: 62,
    once: true,
    title: 'The Evening News',
    text: 'Tansy lay on top of the Hill with the binoculars and reported on the entire village like the evening news. “Tobias is putting the kettle on. AGAIN.”',
    mark: 'grassStain',
    tags: ['watching'],
  },
  {
    id: 'bino_tobias',
    object: 'binoculars',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'Naming the Swifts',
    text: 'Tobias spent the afternoon on the bench at the top of the Hill with the binoculars, watching the swifts. {other} sat down beside him, and they took turns naming them. None of the names were sensible.',
    mark: 'scratch',
    tags: ['birds'],
  },
  {
    id: 'bino_hollis',
    object: 'binoculars',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 60,
    once: true,
    title: 'Somebody Should',
    text: 'Hollis borrowed back his uncle’s binoculars and still couldn’t see a thing through them, so he handed them straight to {other}, who described the whole view. Hollis added all of it to the map.',
    mark: 'label',
    markNote: 'for someone who can see — H.U.',
    tags: ['map'],
  },
  {
    id: 'bino_barnaby',
    object: 'binoculars',
    resident: 'barnaby',
    priority: 60,
    once: true,
    title: 'A Queue, Very Small',
    text: 'Barnaby took the binoculars up the Hill and found his own bakery, very small, with a queue outside it. He was so moved he went straight back down to serve it.',
    mark: 'flourPrint',
    tags: ['watching'],
  },
  {
    id: 'bino_social',
    chance: 0.5,
    object: 'binoculars',
    other: { kind: 'any' },
    priority: 22,
    title: 'Waving Back',
    text: '{name} took the binoculars up the Hill and saw, far below, {other} waving. {name} waved back. {other} came up to see what was so interesting, and it turned out to be the view.',
    mark: 'grassStain',
    tags: ['watching'],
  },
  {
    id: 'bino_solo',
    object: 'binoculars',
    priority: 10,
    title: 'Small and Busy and Dear',
    text: '{name} looked at Mosswick through the binoculars from the top of the Hill. It looked small and busy and very dear.',
    mark: 'grassStain',
    tags: ['watching'],
  },
]

const album: EchoDef[] = [
  {
    id: 'album_odile',
    object: 'album',
    resident: 'odile',
    flags: ['barnaby_photo_odile'],
    other: { kind: 'resident', id: 'barnaby' },
    priority: 88,
    once: true,
    location: 'green',
    title: 'The Scone',
    text: 'In the album, Odile found herself: mid-stride on the Green, faintly outraged, photographed by Barnaby. She looked at it for a long time. Then she walked into the bakery and asked for a scone. The first in twenty years.',
    mark: 'photo',
    tags: ['album'],
    flagsSet: ['odile_scone'],
  },
  {
    id: 'album_hollis',
    object: 'album',
    resident: 'hollis',
    other: { kind: 'photoSubject' },
    priority: 74,
    once: true,
    title: 'Learning Mosswick by Its Faces',
    text: 'Hollis sat up late with the album, learning Mosswick by its faces. In the morning he went round to {other}’s, to say he had seen their photograph and they looked happy in it. They did. They do.',
    mark: 'photo',
    tags: ['album'],
  },
  {
    id: 'album_tobias',
    object: 'album',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 66,
    once: true,
    title: 'In the Background',
    text: 'Tobias turned the album’s pages slowly. He knew everybody in it. He was in some of them, in the background, and hadn’t known. He spent the evening showing {other} which ones.',
    mark: 'photo',
    tags: ['album', 'memory'],
  },
  {
    id: 'album_social',
    object: 'album',
    other: { kind: 'photoSubject' },
    priority: 50,
    title: 'The One of Them',
    text: '{name} looked through the album — {photoCount} photographs now — and ended up at {other}’s door, holding the one of them. “I thought you’d like to see it,” {name} said. {other} did.',
    mark: 'photo',
    tags: ['album'],
  },
  {
    id: 'album_solo',
    object: 'album',
    priority: 10,
    title: 'Bigger in Pictures',
    text: '{name} leafed through the album: all of Mosswick in little squares. It isn’t a big village. It looks bigger in pictures.',
    mark: 'photo',
    tags: ['album'],
  },
]

const sewingBasket: EchoDef[] = [
  {
    id: 'sew_odile',
    object: 'sewingBasket',
    resident: 'odile',
    other: { kind: 'resident', id: 'barnaby' },
    priority: 68,
    once: true,
    location: 'green',
    title: 'Left “Accidentally” on the Counter',
    text: 'Odile mended her satchel strap, then every strap in the post office, then Barnaby’s apron, which he had left “accidentally” on her counter.',
    mark: 'button',
    tags: ['sewing'],
    mend: true,
  },
  {
    id: 'sew_hollis',
    object: 'sewingBasket',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 66,
    once: true,
    title: 'Bunting Made of Maps',
    text: 'Hollis sewed bunting for Lantern Night out of old maps. Every flag is somewhere. {other} found their own house on one and has asked to keep it.',
    mark: 'button',
    tags: ['sewing', 'map'],
    flagsSet: ['map_bunting'],
  },
  {
    id: 'sew_tansy',
    object: 'sewingBasket',
    resident: 'tansy',
    other: { kind: 'resident', id: 'tobias' },
    priority: 64,
    once: true,
    title: 'Moon-Shaped Patches',
    text: 'Tansy sewed a moon-shaped patch onto her raincoat. Then one onto Tobias’s cardigan, while he was still in it. He has decided to leave it there.',
    mark: 'patch',
    tags: ['sewing', 'moon'],
    mend: true,
  },
  {
    id: 'sew_margo',
    object: 'sewingBasket',
    resident: 'margo',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'A Squash-Shaped Patch',
    text: 'Margo sewed a patch onto her dungarees shaped like a squash. It is the first decoration she has ever put on anything. {other} said it suited her. She is pretending she didn’t hear.',
    mark: 'patch',
    tags: ['sewing'],
    mend: true,
  },
  {
    id: 'sew_tobias',
    object: 'sewingBasket',
    resident: 'tobias',
    other: { kind: 'any' },
    priority: 62,
    once: true,
    title: 'Because the Needle Was Threaded',
    text: 'Tobias darned the elbows of his cardigan, then the elbows of {other}’s, and then — because the needle was threaded — a sock he found on the Green.',
    mark: 'button',
    tags: ['sewing'],
    mend: true,
  },
  {
    id: 'sew_barnaby',
    object: 'sewingBasket',
    resident: 'barnaby',
    priority: 62,
    once: true,
    title: 'The Badger Glove',
    text: 'Barnaby sewed a new oven glove in the shape of a badger. It is enormous. It is the best thing he has ever made that isn’t bread.',
    mark: 'flourPrint',
    tags: ['sewing'],
  },
  {
    id: 'sew_social',
    chance: 0.5,
    object: 'sewingBasket',
    other: { kind: 'any' },
    priority: 22,
    title: 'Until It Was Better',
    text: '{name} mended a hem, then a pocket, then {other}’s scarf, which {other} hadn’t known needed mending until it was better.',
    mark: 'button',
    tags: ['sewing'],
    mend: true,
  },
  {
    id: 'sew_solo',
    object: 'sewingBasket',
    priority: 10,
    title: 'The Button Jar',
    text: '{name} sewed a button back on, then another, then kept going until the button jar was empty.',
    mark: 'button',
    tags: ['sewing'],
    mend: true,
  },
]

const flowerPress: EchoDef[] = [
  {
    id: 'press_margo',
    object: 'flowerPress',
    resident: 'margo',
    other: { kind: 'resident', id: 'odile' },
    priority: 70,
    once: true,
    title: 'Violets by Post',
    text: 'Margo pressed the first violets from the reopened Glasshouse and posted one to everybody who had asked after it. Odile delivered them all, and kept one back, which Margo allowed.',
    keepsake: true,
    mark: 'pressedFlower',
    tags: ['flowers'],
    returnsIn: 2,
  },
  {
    id: 'press_hollis',
    object: 'flowerPress',
    resident: 'hollis',
    other: { kind: 'any' },
    priority: 66,
    once: true,
    location: 'kettleRow',
    title: 'Where Each One Grows',
    text: 'Hollis pressed one flower from every garden on Kettle Row — with permission — and glued each onto his map, exactly where it grows. {other} checked his work and found it perfect.',
    keepsake: true,
    mark: 'pressedFlower',
    tags: ['flowers', 'map'],
    returnsIn: 2,
  },
  {
    id: 'press_odile',
    object: 'flowerPress',
    resident: 'odile',
    other: { kind: 'any' },
    priority: 64,
    once: true,
    title: 'Second-Class Stamp',
    text: 'Odile pressed a sunflower petal, a feather and a violet, labelled all three in her very best handwriting, and posted them to {other} with a second-class stamp.',
    keepsake: true,
    mark: 'pressedFlower',
    tags: ['flowers'],
    returnsIn: 2,
  },
  {
    id: 'press_tobias',
    object: 'flowerPress',
    resident: 'tobias',
    priority: 64,
    once: true,
    location: 'kettleRow',
    title: 'One for Every Summer',
    text: 'Tobias pressed a sweet pea and slid it into the back of Hettie’s old cookbook, where there were already forty others, one for every summer.',
    keepsake: true,
    mark: 'pressedFlower',
    tags: ['flowers', 'memory'],
  },
  {
    id: 'press_barnaby',
    object: 'flowerPress',
    resident: 'barnaby',
    priority: 62,
    once: true,
    location: 'green',
    title: 'Shortbread Research',
    text: 'Barnaby pressed lavender “for research purposes.” The research is lavender shortbread. The results are extremely promising.',
    keepsake: true,
    mark: 'flourPrint',
    tags: ['flowers'],
    returnsIn: 2,
    flagsSet: ['lavender_shortbread'],
  },
  {
    id: 'press_tansy',
    object: 'flowerPress',
    resident: 'tansy',
    priority: 62,
    once: true,
    title: 'Mid-Puff',
    text: 'Tansy pressed a dandelion clock mid-puff, which should not be possible. She says she was very quick.',
    keepsake: true,
    mark: 'pressedFlower',
    tags: ['flowers'],
  },
  {
    id: 'press_social',
    chance: 0.5,
    object: 'flowerPress',
    other: { kind: 'any' },
    priority: 22,
    title: 'On the Mantelpiece',
    text: '{name} pressed flowers from the Glasshouse and tucked one into a letter to {other}. {other} put it on the mantelpiece.',
    keepsake: { text: 'a Glasshouse flower, pressed for {other}' },
    mark: 'pressedFlower',
    tags: ['flowers'],
    returnsIn: 2,
  },
  {
    id: 'press_solo',
    object: 'flowerPress',
    priority: 10,
    title: 'Mostly Waiting',
    text: '{name} pressed a handful of flowers between the boards and waited. Pressing flowers is mostly waiting. {They} turned out to be good at it.',
    keepsake: { text: 'a handful of hedgerow flowers' },
    mark: 'pressedFlower',
    tags: ['flowers'],
    returnsIn: 2,
  },
]

const starChart: EchoDef[] = [
  {
    id: 'chart_tansy',
    object: 'starChart',
    resident: 'tansy',
    clearNight: true,
    other: { kind: 'resident', id: 'tobias' },
    priority: 84,
    once: true,
    title: 'A Very Dim One',
    text: 'Tansy found Gerald on the star chart (it is the Moon) and named the dimmest star beside it “Tobias,” because it looked patient. When she told him, Tobias had to sit down for a minute. “Someone else named that one for me, once,” he said.',
    keepsake: { text: '“Tobias” (a very dim star, next to Gerald)' },
    mark: 'starSticker',
    tags: ['stargazing'],
  },
  {
    id: 'chart_social',
    chance: 0.5,
    object: 'starChart',
    clearNight: true,
    other: { kind: 'any' },
    priority: 30,
    title: 'Named by Committee',
    text: '{name} unrolled the star chart on the Hill. The club had pencilled in constellations of its own — {latest} among them. {name} added one more, and {other} came up the Hill to argue about it.',
    keepsake: true,
    mark: 'starSticker',
    tags: ['stargazing'],
  },
  {
    id: 'chart_cloudy',
    object: 'starChart',
    clearNight: false,
    priority: 30,
    title: 'A Storybook With No Words',
    text: 'The sky was all cloud, so {name} read the star chart by lamplight instead, like a storybook with no words, and added a constellation from memory.',
    keepsake: true,
    mark: 'waxDrip',
    tags: ['stargazing'],
  },
  {
    id: 'chart_solo',
    object: 'starChart',
    priority: 10,
    title: 'One More Constellation',
    text: '{name} took the star chart up the Hill and matched every dot {they} could see to a dot on the paper, then made up a constellation of {their} own.',
    keepsake: true,
    mark: 'starSticker',
    tags: ['stargazing'],
  },
]

/** Odile's birthday, whatever you lend her. */
const birthday: EchoDef[] = [
  {
    id: 'odile_birthday_any',
    object: [...OBJECT_IDS],
    resident: 'odile',
    requests: ['odile_birthday'],
    other: { kind: 'any' },
    priority: 66,
    once: true,
    title: 'Something She Would Never Do',
    text: 'For her birthday, Odile did something she would never, ever do: she took the {obj} out, told {other} it was her birthday, and let {other} make a fuss. She says she didn’t enjoy it. She is lying, and she knows everyone knows.',
    mark: 'ribbon',
    tags: ['birthday'],
    flagsSet: ['odile_told_birthday'],
  },
]

/**
 * Trace Echoes: for every object, finding what the last borrower left behind
 * (a keepsake inside it, or a mark on it) and following it back to them.
 * The wording comes from each object's `trace` sentences plus the borrower's
 * own way of reaching out (`social` in residents.ts).
 */
const traces: EchoDef[] = OBJECT_IDS.map((id) => ({
  id: `trace_${id}`,
  object: id,
  other: { kind: 'trace' as const },
  // Sky things only make sense to follow on a night you can see the sky.
  clearNight: OBJECTS[id].tags.includes('sky') && OBJECTS[id].time === 'night' ? true : undefined,
  priority: 62,
  title: OBJECTS[id].trace.title,
  text: '{traceFound} {social}',
  mark: OBJECTS[id].defaultMark,
  keepsake: OBJECTS[id].traceKeepsake ?? (OBJECTS[id].keepsakeKind ? true : undefined),
  tags: ['trace'],
}))

export const ECHOES: EchoDef[] = [
  ...telescope,
  ...blanket,
  ...camera,
  ...recordPlayer,
  ...cakeTin,
  ...kite,
  ...boardGame,
  ...thermos,
  ...lantern,
  ...umbrella,
  ...paints,
  ...gardenKit,
  ...toolbox,
  ...birdGuide,
  ...binoculars,
  ...album,
  ...sewingBasket,
  ...flowerPress,
  ...starChart,
  ...birthday,
  ...traces,
]
