import type { JointEchoDef } from '../defs'

/*
 * JOINT ECHOES — when two things lent on the same day meet out in the world.
 * These reward noticing where people are headed ("Up the Hill tonight…").
 * Templates: {a} {b} (borrowers), {objA} {objB}.
 */
export const JOINT_ECHOES: JointEchoDef[] = [
  {
    id: 'joint_hill_lantern',
    a: { object: ['telescope', 'starChart'] },
    b: { object: ['lantern'] },
    clearNight: true,
    priority: 85,
    once: true,
    location: 'hill',
    time: 'night',
    fx: 'stars',
    title: 'Everything They Needed',
    text: 'Up on Observatory Hill, {a} had the {objA} and {b} had the lantern, and between them they had everything they needed. {b} held the light while {a} found the Moon; then they swapped. They stayed until the dew came down.',
    markA: 'starSticker',
    markB: 'waxDrip',
    tags: ['stargazing'],
  },
  {
    id: 'joint_cocoa_hill',
    a: { object: ['telescope', 'starChart', 'binoculars'] },
    b: { object: ['thermos'] },
    clearNight: true,
    priority: 84,
    once: true,
    location: 'hill',
    time: 'night',
    fx: 'steam',
    title: 'Cocoa and Saturn',
    text: '{b} carried the thermos up the Hill and {a} carried the {objA}, and neither of them had planned it. Hot cocoa and a sky full of planets. There are worse ways to spend an evening, and they couldn’t think of a better one.',
    markA: 'starSticker',
    markB: 'teaRing',
    tags: ['stargazing'],
  },
  {
    id: 'joint_feast',
    a: { object: ['blanket'] },
    b: { object: ['cakeTin'] },
    notWeather: ['rainy'],
    priority: 84,
    once: true,
    location: 'millpond',
    time: 'day',
    fx: 'petals',
    title: 'The Accidental Feast',
    text: '{a} spread the picnic blanket by the Millpond, and {b} came by with a cake in the old tin. “I was only passing,” {b} said, which nobody believed. It became the longest lunch in Mosswick history.',
    markA: 'jamStain',
    markB: 'jamStain',
    keepsakeB: true,
    tags: ['picnic', 'baking'],
  },
  {
    id: 'joint_rain_game',
    a: { object: ['umbrella'] },
    b: { object: ['boardGame'] },
    weather: ['rainy'],
    priority: 84,
    once: true,
    location: 'homeA',
    time: 'dusk',
    indoor: true,
    fx: 'confetti',
    title: 'Come In, I’ve Got Snails & Ladders',
    text: '{a} walked {b} home under the big green umbrella, and at the door {b} said, “Come in — I’ve got Snails & Ladders.” The rain went on all evening. So did the game.',
    markA: 'mudSplash',
    markB: 'teaRing',
    keepsakeB: { text: '{B} 3 · {A} 3 (rained off)' },
    tags: ['rain', 'games'],
  },
  {
    id: 'joint_dance',
    a: { object: ['recordPlayer'] },
    b: { object: ['blanket', 'lantern'] },
    weather: ['sunny', 'windy'],
    priority: 86,
    once: true,
    location: 'green',
    time: 'dusk',
    fx: 'notes',
    title: 'A Dance on the Green',
    text: '{a} brought the record player; {b} brought the {objB}; the Green did the rest. By dusk there was dancing, and by dark there was a queue to dance with {b}.',
    markA: 'grassStain',
    markB: 'grassStain',
    keepsakeA: true,
    tags: ['music', 'dance'],
    flagsSet: ['dance_on_green'],
  },
  {
    id: 'joint_kite_photo',
    a: { object: ['camera'] },
    b: { object: ['kite'] },
    weather: ['windy'],
    priority: 84,
    once: true,
    location: 'hill',
    time: 'day',
    fx: 'leaves',
    title: 'Mostly Sky',
    text: '{b} got the kite so high that {a} had to lie flat on the grass to photograph it. The photograph is mostly sky and a small red dot, and it is perfect.',
    markA: 'grassStain',
    markB: 'knot',
    keepsakeA: { text: 'a kite, very high, flown by {B}', subject: 'other' },
    tags: ['kite', 'photo'],
  },
  {
    id: 'joint_paint_picnic',
    a: { object: ['paints'] },
    b: { object: ['blanket', 'thermos', 'birdGuide'] },
    notWeather: ['rainy'],
    priority: 83,
    once: true,
    location: 'millpond',
    time: 'day',
    fx: 'sparkle',
    title: 'Sat Still for Once',
    text: 'At the Millpond, {a} set up the watercolours and found {b} already there with the {objB}. {b} was painted, very slowly, sitting still for once. It is the best page in the sketchbook.',
    markA: 'paintDab',
    markB: 'paintDab',
    keepsakeA: { text: '{B} by the Millpond, sitting still for once', subject: 'other' },
    tags: ['painting'],
  },
  {
    id: 'joint_glasshouse',
    a: { object: ['toolbox'] },
    b: { object: ['gardenKit', 'thermos', 'recordPlayer'] },
    closed: 'glasshouse',
    priority: 89,
    once: true,
    location: 'glasshouse',
    time: 'day',
    fx: 'sparkle',
    title: 'Two Pairs of Hands',
    text: '{a} and {b} met at the jammed Glasshouse door by accident: {a} with the toolbox, {b} with the {objB}. It took two pairs of hands and one argument about which way a hinge goes. The door opened with a sigh that everyone on the Green heard.',
    markA: 'scratch',
    markB: 'mudSplash',
    tags: ['repair', 'glasshouse'],
    flagsSet: ['glasshouse_open'],
  },
  {
    id: 'joint_birds',
    a: { object: ['birdGuide'] },
    b: { object: ['binoculars'] },
    priority: 84,
    once: true,
    location: 'millpond',
    time: 'day',
    title: 'One Looks, One Reads',
    text: '{b} had the binoculars and {a} had the bird guide, so {b} looked and {a} read, and between them they identified the kingfisher, two grebes, and something that was almost certainly a moorhen.',
    markA: 'feather',
    markB: 'feather',
    keepsakeA: { text: 'Kingfisher, grebe, grebe, moorhen (probably). — {A} & {B}' },
    tags: ['birds'],
  },
  {
    id: 'joint_party',
    a: { object: ['recordPlayer'] },
    b: { object: ['cakeTin', 'album'] },
    priority: 83,
    once: true,
    location: 'homeA',
    time: 'dusk',
    indoor: true,
    fx: 'confetti',
    title: 'A Party, Technically',
    text: '{a} had music on, and {b} turned up with the {objB}. Nobody called it a party, but there was music, and people kept arriving, so technically it was.',
    markA: 'noteSticker',
    markB: 'jamStain',
    keepsakeA: true,
    tags: ['music', 'host'],
  },
]
