import type { ObjectDef, ObjectId } from '../types'

// Every lendable thing in the Borrowburrow. `trace` sentences are used when a
// later borrower discovers what an earlier borrower left behind.
export const OBJECTS: Record<ObjectId, ObjectDef> = {
  telescope: {
    id: 'telescope',
    name: 'Old Brass Telescope',
    short: 'telescope',
    catalogue: '001',
    blurb: 'Brass, a little dented, still sharp. The tripod sulks in the cold.',
    tags: ['sky', 'night', 'wonder', 'curious', 'quiet'],
    color: '#c9a24a',
    home: 'hill',
    time: 'night',
    mode: 'stand',
    defaultMark: 'starSticker',
    fx: 'stars',
    origin: 'Given to the Borrowburrow by Tobias & Hettie Crumb, many summers ago.',
    originBy: 'tobias',
    trace: {
      title: 'Still Pointed at Something',
      mark: 'The telescope still wore {other}’s {mark}, and it was still aimed at the exact patch of sky {other} had left it on. When {name} looked, there was something there.',
    },
    starting: true,
  },
  blanket: {
    id: 'blanket',
    name: 'Red Checkered Picnic Blanket',
    short: 'picnic blanket',
    catalogue: '002',
    blurb: 'Big enough for four, or for two and a great many sandwiches.',
    tags: ['outdoors', 'social', 'food', 'rest', 'sunny'],
    color: '#c8463a',
    home: 'millpond',
    time: 'day',
    mode: 'ground',
    defaultMark: 'jamStain',
    fx: 'petals',
    origin: 'Came with the Borrowburrow. Nobody knows whose it was first.',
    trace: {
      title: 'Crumbs of Evidence',
      mark: 'Caught in the weave of the blanket was {other}’s {mark}, from {other}’s last outing with it.',
    },
    starting: true,
  },
  camera: {
    id: 'camera',
    name: 'Instant Camera',
    short: 'camera',
    catalogue: '003',
    blurb: 'Whirrs, clicks, and hands you a picture while you’re still smiling.',
    tags: ['memory', 'creative', 'curious', 'social', 'adventure'],
    color: '#4f8a8b',
    home: 'green',
    time: 'day',
    mode: 'held',
    defaultMark: 'scratch',
    fx: 'flash',
    keepsakeKind: 'photo',
    keepsakeLabel: 'Photographs taken',
    origin: 'Found in a box marked FRAGILE (PROBABLY).',
    trace: {
      title: 'A Photo Left in the Tray',
      keepsake: 'One photograph was still in the camera’s tray — {keepsake} — taken by {other}.',
      mark: 'The camera still wore {other}’s {mark}.',
    },
    traceKeepsake: { text: '{other}, holding up the photograph {name} found', subject: 'other' },
    starting: true,
  },
  recordPlayer: {
    id: 'recordPlayer',
    name: 'Portable Record Player',
    short: 'record player',
    catalogue: '004',
    blurb: 'A suitcase that plays music. Whoever borrows it leaves a record in the lid.',
    tags: ['music', 'social', 'host', 'indoor', 'comfort', 'dance'],
    color: '#8a4f7d',
    home: 'home',
    time: 'dusk',
    indoor: true,
    mode: 'ground',
    defaultMark: 'noteSticker',
    fx: 'notes',
    keepsakeKind: 'record',
    keepsakeLabel: 'Records left in the lid',
    origin: 'Won at the 1971 tombola by persons unknown.',
    trace: {
      title: 'A Record Left in the Lid',
      keepsake: 'Inside the lid, {name} found {other}’s record — {keepsake} — and played it until {they} knew it by heart.',
      mark: 'The record player still wore {other}’s {mark}.',
    },
    starting: true,
  },
  cakeTin: {
    id: 'cakeTin',
    name: 'Floral Cake Tin',
    short: 'cake tin',
    catalogue: '005',
    blurb: 'Dented at the 1987 fête. A recipe card inside the lid, with notes in several hands.',
    tags: ['food', 'gift', 'host', 'social', 'comfort'],
    color: '#6d8fc0',
    home: 'home',
    time: 'day',
    indoor: true,
    mode: 'held',
    defaultMark: 'jamStain',
    fx: 'steam',
    keepsakeKind: 'recipe',
    keepsakeLabel: 'Notes on the recipe card',
    origin: 'Mosswick Village Fête, 1987. The dent is from the tombola.',
    trace: {
      title: 'Notes in the Margin',
      keepsake: 'On the recipe card inside the lid, in {other}’s hand: “{keepsake}” {name} followed it to the letter.',
      mark: 'The tin still wore {other}’s {mark}.',
    },
    starting: true,
  },
  kite: {
    id: 'kite',
    name: 'Box Kite',
    short: 'kite',
    catalogue: '006',
    blurb: 'Red and saffron, with a tail of knotted bows. Pulls like a dog on a walk.',
    tags: ['wind', 'outdoors', 'sky', 'play', 'adventure'],
    color: '#d9622b',
    home: 'hill',
    time: 'day',
    mode: 'sky',
    defaultMark: 'knot',
    fx: 'leaves',
    origin: 'Built by the Kettle Row children, summer of 1983. Repaired many times since.',
    trace: {
      title: 'A Particular Knot',
      mark: 'The kite’s tail still carried {other}’s {mark}, and the string was tied off with {other}’s knot — a fussy knot nobody else in Mosswick uses.',
    },
    starting: true,
  },
  boardGame: {
    id: 'boardGame',
    name: 'Snails & Ladders',
    short: 'board game',
    catalogue: '007',
    blurb: 'A game of patience, luck and extremely slow racing. Score sheet in the lid.',
    tags: ['social', 'indoor', 'host', 'play', 'rain'],
    color: '#6f8f45',
    home: 'home',
    time: 'dusk',
    indoor: true,
    mode: 'ground',
    defaultMark: 'teaRing',
    fx: 'confetti',
    keepsakeKind: 'score',
    keepsakeLabel: 'The score sheet',
    origin: 'Donated by the Mosswick Snails & Ladders League (disbanded after the Incident).',
    trace: {
      title: 'The Score Sheet',
      keepsake: 'The score sheet in the lid said, in {other}’s writing: “{keepsake}” This could not be allowed to stand.',
      mark: 'The box still wore {other}’s {mark}.',
    },
    traceKeepsake: { text: '{NAME} 1 · {OTHER} 1 (a draw, somehow)' },
    starting: true,
  },
  thermos: {
    id: 'thermos',
    name: 'Tartan Thermos',
    short: 'thermos',
    catalogue: '008',
    blurb: 'Keeps tea hot for six hours and cocoa hot forever.',
    tags: ['comfort', 'outdoors', 'fog', 'quiet', 'social', 'cold'],
    color: '#3f6f5a',
    home: 'millpond',
    time: 'day',
    mode: 'held',
    defaultMark: 'teaRing',
    fx: 'steam',
    origin: 'Left on the doorstep with a label: “FOR WHOEVER IS COLD.”',
    trace: {
      title: 'Somebody Else’s Cocoa',
      mark: 'The thermos still smelled faintly of {other}’s cocoa, and wore {other}’s {mark}.',
    },
    starting: true,
  },
  lantern: {
    id: 'lantern',
    name: 'Camping Lantern',
    short: 'lantern',
    catalogue: '009',
    blurb: 'Brass and glass. Turns the dark into a room you can walk around in.',
    tags: ['night', 'dark', 'outdoors', 'comfort', 'adventure'],
    color: '#e6a33e',
    home: 'kettleRow',
    time: 'night',
    mode: 'held',
    defaultMark: 'waxDrip',
    fx: 'moths',
    origin: 'From the old Mosswick scout hut, when it became the new Mosswick scout hut.',
    trace: {
      title: 'Soot and Moth-Dust',
      mark: 'The lantern glass still carried {other}’s {mark}, and a moth that seemed to know the way to {other}’s house.',
    },
    starting: true,
  },
  umbrella: {
    id: 'umbrella',
    name: 'Big Green Umbrella',
    short: 'umbrella',
    catalogue: '010',
    blurb: 'Room for two, if they’re fond of each other.',
    tags: ['rain', 'walk', 'outdoors', 'social'],
    color: '#2f6b4a',
    home: 'green',
    time: 'day',
    mode: 'overhead',
    defaultMark: 'mudSplash',
    origin: 'Left behind at the 1990 Harvest Supper. Never claimed. Now everyone’s.',
    trace: {
      title: 'Initials on the Handle',
      mark: 'The umbrella still wore {other}’s {mark}, and {other}’s initials, scratched small on the handle.',
    },
    starting: true,
  },
  paints: {
    id: 'paints',
    name: 'Watercolour Tin & Sketchbook',
    short: 'watercolours',
    catalogue: '011',
    blurb: 'Twelve colours, one brush, and a sketchbook half-full of other people’s afternoons.',
    tags: ['creative', 'quiet', 'hobby', 'nature'],
    color: '#5b7fb5',
    home: 'millpond',
    time: 'day',
    mode: 'easel',
    defaultMark: 'paintDab',
    fx: 'sparkle',
    keepsakeKind: 'painting',
    keepsakeLabel: 'Pages in the sketchbook',
    origin: 'Given by a travelling painter who stayed one night and paid in paint.',
    trace: {
      title: 'Someone Else’s Page',
      keepsake: 'Flicking through the sketchbook, {name} found {other}’s painting: {keepsake}.',
      mark: 'The tin still wore {other}’s {mark}.',
    },
    traceKeepsake: { text: '{other}, painted from memory', subject: 'other' },
    starting: true,
  },
  gardenKit: {
    id: 'gardenKit',
    name: 'Gardening Trug',
    short: 'gardening trug',
    catalogue: '012',
    blurb: 'Trowel, gloves, twine, and a tin of seeds that rattles hopefully.',
    tags: ['grow', 'nature', 'outdoors', 'hobby', 'gift', 'home'],
    color: '#8a6a3b',
    home: 'green',
    time: 'day',
    mode: 'ground',
    defaultMark: 'mudSplash',
    fx: 'petals',
    keepsakeKind: 'planting',
    keepsakeLabel: 'Seed packets, labelled',
    origin: 'Assembled by the Mosswick Allotment Society. Mostly by one member of it.',
    trace: {
      title: 'A Seed Packet, Labelled',
      keepsake: 'Tucked in the trug was a seed packet labelled in {other}’s hand: {keepsake}.',
      mark: 'The trug still wore {other}’s {mark}.',
    },
    traceKeepsake: { text: 'A SWAP — seeds from {other}’s garden' },
    starting: true,
  },
  toolbox: {
    id: 'toolbox',
    name: 'Red Toolbox',
    short: 'toolbox',
    catalogue: '013',
    blurb: 'Everything for fixing, plus a spirit level with opinions.',
    tags: ['repair', 'useful', 'hobby'],
    color: '#b8433a',
    home: 'home',
    time: 'day',
    indoor: true,
    mode: 'ground',
    defaultMark: 'scratch',
    fx: 'sparkle',
    origin: 'Tobias Crumb’s second-best toolbox.',
    originBy: 'tobias',
    trace: {
      title: 'Put Back Tidier',
      mark: '{other} had left the toolbox tidier than they found it, and it still wore {other}’s {mark}.',
    },
    starting: false,
  },
  birdGuide: {
    id: 'birdGuide',
    name: 'Field Guide to Hedge & Water Birds',
    short: 'bird guide',
    catalogue: '014',
    blurb: 'Well-thumbed. Pencilled ticks in the margins from every borrower.',
    tags: ['nature', 'quiet', 'curious', 'hobby', 'walk'],
    color: '#4c7a5c',
    home: 'millpond',
    time: 'day',
    mode: 'held',
    defaultMark: 'feather',
    keepsakeKind: 'note',
    keepsakeLabel: 'Pencil notes in the margins',
    origin: 'Odile Fenn’s own copy. She is on page 41.',
    originBy: 'odile',
    trace: {
      title: 'Pencil in the Margins',
      keepsake: 'In the margin, in {other}’s pencil: “{keepsake}”',
      mark: 'The guide still held {other}’s {mark} between its pages.',
    },
    starting: false,
  },
  binoculars: {
    id: 'binoculars',
    name: 'Field Binoculars',
    short: 'binoculars',
    catalogue: '015',
    blurb: 'Brings far things near and near things into focus.',
    tags: ['nature', 'curious', 'sky', 'walk', 'adventure'],
    color: '#5a5550',
    home: 'hill',
    time: 'day',
    mode: 'held',
    defaultMark: 'grassStain',
    origin: 'Belonged to Hollis Underfield’s uncle, who could see.',
    originBy: 'hollis',
    trace: {
      title: 'Focused for Someone Else',
      mark: 'The binoculars were still focused for {other}’s eyes, and wore {other}’s {mark}.',
    },
    starting: false,
  },
  album: {
    id: 'album',
    name: 'Photo Album',
    short: 'photo album',
    catalogue: '016',
    blurb: 'Every photograph the instant camera has taken, in order.',
    tags: ['memory', 'social', 'quiet', 'indoor'],
    color: '#7a4b2c',
    home: 'home',
    time: 'dusk',
    indoor: true,
    mode: 'lap',
    defaultMark: 'photo',
    origin: 'Hettie Crumb’s old album, given so the photographs have somewhere to live.',
    originBy: 'tobias',
    trace: {
      title: 'A Bookmark',
      mark: 'The album still held {other}’s {mark}, marking a page.',
    },
    starting: false,
  },
  sewingBasket: {
    id: 'sewingBasket',
    name: 'Sewing Basket',
    short: 'sewing basket',
    catalogue: '017',
    blurb: 'Buttons, thread, and a pincushion hedgehog (no relation).',
    tags: ['repair', 'creative', 'gift', 'quiet', 'indoor'],
    color: '#c77d8f',
    home: 'home',
    time: 'dusk',
    indoor: true,
    mode: 'lap',
    defaultMark: 'button',
    origin: 'Barnaby Holt’s nan’s basket. He only ever used it for icing bags.',
    originBy: 'barnaby',
    trace: {
      title: 'A Half-Finished Thing',
      mark: 'In the basket, beside {other}’s {mark}, was a half-finished mitten in {other}’s colours.',
    },
    starting: false,
  },
  flowerPress: {
    id: 'flowerPress',
    name: 'Flower Press',
    short: 'flower press',
    catalogue: '018',
    blurb: 'Two boards, four wing-nuts, and a great deal of patience.',
    tags: ['nature', 'creative', 'gift', 'memory', 'quiet'],
    color: '#9a6fb0',
    home: 'glasshouse',
    time: 'day',
    mode: 'held',
    defaultMark: 'pressedFlower',
    fx: 'petals',
    keepsakeKind: 'pressed',
    keepsakeLabel: 'Pressed between the boards',
    origin: 'From the Glasshouse potting shed, the day the door opened again.',
    originBy: 'margo',
    trace: {
      title: 'Pressed Between the Boards',
      keepsake: 'Between the boards, {name} found {other}’s pressing: {keepsake}.',
      mark: 'The press still wore {other}’s {mark}.',
    },
    starting: false,
  },
  starChart: {
    id: 'starChart',
    name: 'Star Chart',
    short: 'star chart',
    catalogue: '019',
    blurb: 'Hand-inked by the Mosswick Astronomy Club. Constellations named by committee.',
    tags: ['sky', 'night', 'wonder', 'curious'],
    color: '#34466b',
    home: 'hill',
    time: 'night',
    mode: 'held',
    defaultMark: 'starSticker',
    fx: 'stars',
    keepsakeKind: 'constellation',
    keepsakeLabel: 'Constellations named',
    origin: 'The Mosswick Astronomy Club’s first chart.',
    trace: {
      title: 'A Pencilled Constellation',
      keepsake: 'On the chart, in {other}’s pencil, a new constellation: {keepsake}.',
      mark: 'The chart still wore {other}’s {mark}.',
    },
    starting: false,
  },
}

export const STARTING_OBJECTS: ObjectId[] = (Object.keys(OBJECTS) as ObjectId[]).filter(
  (id) => OBJECTS[id].starting,
)
