import type { LocationId, ResidentId, Weather } from '../types'

export interface RequestDef {
  id: string
  resident: ResidentId
  /** What they say at the counter. Never names the object they want. */
  text: string
  /** Short summary shown on Echo cards: "wanted to see the Moon properly". */
  gist: string
  tags: string[]
  /** Overheard line for the morning notice board. */
  hint: string
  weather?: Weather[]
  minDay?: number
  maxDay?: number
  /** Only offered on exactly this day (tutorial, arrivals, Lantern Night). */
  day?: number
  flags?: string[]
  notFlags?: string[]
  locationClosed?: LocationId
  priority?: number
  repeatable?: boolean
}

export const REQUESTS: RequestDef[] = [
  // ——— Tansy ———
  {
    id: 'tansy_moon',
    resident: 'tansy',
    text: 'I’m going to look at the Moon properly tonight. Not just “oh, there it is.” PROPERLY.',
    gist: 'wanted to see the Moon properly',
    tags: ['sky', 'night', 'curious', 'wonder', 'memory'],
    hint: 'Tansy has been asking everyone exactly how far away the Moon is.',
    day: 1,
  },
  {
    id: 'tansy_underfoot',
    resident: 'tansy',
    text: 'Mum says I’m “under her feet.” I would like to be under somebody else’s feet today, please.',
    gist: 'needed to be under somebody else’s feet',
    tags: ['play', 'adventure', 'outdoors', 'social'],
    hint: 'Tansy’s mum is looking for somewhere to put Tansy.',
    minDay: 2,
  },
  {
    id: 'tansy_rain',
    resident: 'tansy',
    text: 'It’s raining, which means I’m allowed to get as wet as I want. That’s the rule. I made the rule.',
    gist: 'wanted to get as wet as allowed',
    tags: ['rain', 'outdoors', 'play', 'adventure'],
    hint: 'Tansy has been spotted testing puddles for depth.',
    weather: ['rainy'],
  },
  {
    id: 'tansy_evidence',
    resident: 'tansy',
    text: 'Something lives under the jetty at the Millpond and I need EVIDENCE.',
    gist: 'needed evidence of the thing under the jetty',
    tags: ['curious', 'nature', 'adventure', 'memory'],
    hint: 'Tansy is “investigating” the Millpond jetty.',
    minDay: 2,
  },
  {
    id: 'tansy_wind',
    resident: 'tansy',
    text: 'The wind is being SO loud today. I think it wants somebody to play with.',
    gist: 'thought the wind wanted a playmate',
    tags: ['wind', 'play', 'sky', 'outdoors'],
    hint: 'Tansy has been running in circles on the Green with her arms out.',
    weather: ['windy'],
  },
  {
    id: 'tansy_dark',
    resident: 'tansy',
    text: 'I’m not scared of the dark. I just think it should be a bit less dark. Generally.',
    gist: 'wanted the dark to be a bit less dark',
    tags: ['night', 'dark', 'comfort', 'courage'],
    hint: 'Tansy asked Tobias whether the dark “goes all the way down.”',
    minDay: 2,
  },
  {
    id: 'tansy_gift',
    resident: 'tansy',
    text: 'I want to make something for somebody, but it has to be a surprise. Even from me.',
    gist: 'was planning a surprise for somebody',
    tags: ['gift', 'creative', 'food', 'grow'],
    hint: 'Tansy is planning a surprise. She has told everyone.',
    minDay: 3,
  },
  {
    id: 'tansy_again',
    resident: 'tansy',
    text: 'I saw a bright dot that wasn’t a star. It didn’t twinkle. I’ve been thinking about it ALL day.',
    gist: 'was sure she’d seen a planet',
    tags: ['sky', 'night', 'curious', 'wonder'],
    hint: 'Tansy is convinced she saw a planet and won’t hear otherwise.',
    flags: ['tansy_stargazed'],
    weather: ['sunny', 'windy'],
    priority: 4,
  },
  {
    id: 'tansy_festival',
    resident: 'tansy',
    text: 'It’s Lantern Night and I want to be EXTREMELY involved.',
    gist: 'wanted to be extremely involved in Lantern Night',
    tags: ['festival', 'play', 'night', 'social'],
    hint: 'Tansy has been up since five, practising being involved.',
    day: 7,
  },
  {
    id: 'tansy_any',
    resident: 'tansy',
    text: 'I’ve done everything in Mosswick twice. Give me something to do a third time.',
    gist: 'had done everything twice',
    tags: ['play', 'adventure'],
    hint: 'Tansy has run out of things, which never lasts.',
    repeatable: true,
  },

  // ——— Barnaby ———
  {
    id: 'barnaby_rut',
    resident: 'barnaby',
    text: 'Eleven years, same six loaves. I’d like to do something today that isn’t bread. Anything. Within reason. Or not.',
    gist: 'wanted to do anything that wasn’t bread',
    tags: ['hobby', 'creative', 'new', 'outdoors', 'play'],
    hint: 'Barnaby has baked the same six loaves for eleven years and has started to notice.',
    day: 1,
  },
  {
    id: 'barnaby_odile',
    resident: 'barnaby',
    text: 'The postmistress comes in at nine every morning. I’ve said “morning” to her four thousand times. I’d like to say something else.',
    gist: 'wanted to say something other than “morning” to Odile',
    tags: ['social', 'gift', 'courage', 'food'],
    hint: 'Barnaby keeps glancing at the post office and sighing into the dough.',
    minDay: 2,
    priority: 2,
  },
  {
    id: 'barnaby_afternoon',
    resident: 'barnaby',
    text: 'Bakery’s shut till tomorrow. I’ve got a whole afternoon and no idea what people do with those.',
    gist: 'had a whole afternoon and no idea what to do with it',
    tags: ['rest', 'outdoors', 'quiet', 'hobby'],
    hint: 'The bakery shuts early today. Barnaby seems alarmed about it.',
    weather: ['sunny', 'foggy'],
  },
  {
    id: 'barnaby_rain',
    resident: 'barnaby',
    text: 'Rain’s put everyone off buns. I’ll either do something useful or eat my own stock.',
    gist: 'was about to eat his own stock',
    tags: ['indoor', 'host', 'social', 'rain'],
    hint: 'Barnaby is worried about a surplus of buns.',
    weather: ['rainy'],
  },
  {
    id: 'barnaby_recipe',
    resident: 'barnaby',
    text: 'Tobias says my scones “haven’t changed since the Moon landing.” I’d like to prove him wrong. Slightly wrong.',
    gist: 'wanted to prove Tobias slightly wrong about his scones',
    tags: ['food', 'creative', 'gift', 'new'],
    hint: 'Tobias has insulted Barnaby’s scones, gently, with affection.',
    minDay: 3,
  },
  {
    id: 'barnaby_marrow',
    resident: 'barnaby',
    text: 'Margo’s marrow is bigger than mine again. I don’t care. I care a very great deal.',
    gist: 'did not care about Margo’s marrow (he cared a great deal)',
    tags: ['grow', 'rivalry', 'nature', 'social'],
    hint: 'The marrow situation between Barnaby and Margo has escalated.',
    minDay: 3,
  },
  {
    id: 'barnaby_wind',
    resident: 'barnaby',
    text: 'Wind’s blowing the flour off the loaves. Might as well go and stand in it.',
    gist: 'thought he might as well go and stand in the wind',
    tags: ['wind', 'outdoors', 'play'],
    hint: 'Flour has been seen blowing across the Green.',
    weather: ['windy'],
  },
  {
    id: 'barnaby_festival',
    resident: 'barnaby',
    text: 'Lantern Night. I’ve made two hundred buns. I’d like to do one thing tonight that isn’t a bun.',
    gist: 'wanted one thing tonight that wasn’t a bun',
    tags: ['festival', 'social', 'music', 'night'],
    hint: 'Barnaby has made two hundred buns and is looking for a distraction.',
    day: 7,
  },
  {
    id: 'barnaby_any',
    resident: 'barnaby',
    text: 'Surprise me. Not with bread.',
    gist: 'wanted to be surprised, not with bread',
    tags: ['new', 'play'],
    hint: 'Barnaby wants a surprise.',
    repeatable: true,
  },

  // ——— Odile ———
  {
    id: 'odile_early',
    resident: 'odile',
    text: 'I finished the round early. This has never happened. I don’t know what to do with my hands.',
    gist: 'finished the round early and didn’t know what to do with her hands',
    tags: ['rest', 'quiet', 'hobby', 'new'],
    hint: 'The post went out forty minutes early today. Odile seems unsettled.',
    minDay: 2,
  },
  {
    id: 'odile_fog',
    resident: 'odile',
    text: 'Fog today. Everything goes soft and quiet. I’d like to be out in it before it lifts.',
    gist: 'wanted to be out in the fog before it lifted',
    tags: ['fog', 'outdoors', 'quiet', 'walk'],
    hint: 'Odile likes fog. She will not say so.',
    weather: ['foggy'],
  },
  {
    id: 'odile_moon',
    resident: 'odile',
    text: 'I have another letter here addressed to “The Moon, Up There.” Second-class stamp. I’d like to... do something about it.',
    gist: 'wanted to do something about a letter to the Moon',
    tags: ['sky', 'night', 'gift', 'kindness', 'creative'],
    hint: 'The post office has a growing pile of letters for the Moon.',
    minDay: 2,
    priority: 1,
  },
  {
    id: 'odile_rain',
    resident: 'odile',
    text: 'The post is delivered. I’m damp to the knee. I’d like to be undamp somewhere with company. Not too much company.',
    gist: 'wanted to be undamp, with not too much company',
    tags: ['indoor', 'comfort', 'social', 'quiet'],
    hint: 'Odile finished the round soaked and philosophical.',
    weather: ['rainy'],
  },
  {
    id: 'odile_wind',
    resident: 'odile',
    text: 'The wind took three letters from my satchel and put them in the Millpond. I’d like to do something more cheerful with it.',
    gist: 'wanted to do something more cheerful with the wind',
    tags: ['wind', 'outdoors', 'play'],
    hint: 'Three letters were fished out of the Millpond this morning.',
    weather: ['windy'],
  },
  {
    id: 'odile_birthday',
    resident: 'odile',
    text: 'It’s nobody’s business. But it’s my birthday. I’d like to do something I would never, ever do.',
    gist: 'wanted to do something she would never do, on her birthday',
    tags: ['new', 'adventure', 'social', 'gift', 'food'],
    hint: 'Odile has polished her satchel buckle twice this morning. Nobody knows why.',
    minDay: 4,
    maxDay: 6,
    priority: 3,
  },
  {
    id: 'odile_festival',
    resident: 'odile',
    text: 'I have been asked to “join in” tonight. I’m told this is different from “attending.”',
    gist: 'had been asked to join in, not merely attend',
    tags: ['festival', 'social', 'night', 'new'],
    hint: 'Odile has been asked to join in. She is taking advice.',
    day: 7,
  },
  {
    id: 'odile_any',
    resident: 'odile',
    text: 'I have a free hour. I have scheduled it. I’d like it to go well.',
    gist: 'had a scheduled free hour',
    tags: ['quiet', 'rest'],
    hint: 'Odile has scheduled a free hour.',
    repeatable: true,
  },

  // ——— Tobias ———
  {
    id: 'tobias_useful',
    resident: 'tobias',
    text: 'Nobody brings me anything to fix any more. Everything’s either new or broken beyond me.',
    gist: 'wanted something to fix',
    tags: ['repair', 'useful', 'hobby'],
    hint: 'Tobias has fixed his own kettle three times this week, for something to do.',
    minDay: 2,
  },
  {
    id: 'tobias_hill',
    resident: 'tobias',
    text: 'Hettie and I used to walk up the Hill of an evening. I’ve been thinking about doing that again. Slowly.',
    gist: 'wanted to walk up the Hill, the way he and Hettie used to',
    tags: ['sky', 'night', 'memory', 'walk'],
    hint: 'Tobias was seen looking up at Observatory Hill for a long time.',
    minDay: 2,
  },
  {
    id: 'tobias_quiet',
    resident: 'tobias',
    text: 'The house is too quiet. I don’t mind quiet. I mind too quiet.',
    gist: 'found the house too quiet',
    tags: ['comfort', 'social', 'music', 'indoor', 'host'],
    hint: 'Tobias says his house has gone “too quiet.”',
  },
  {
    id: 'tobias_fog',
    resident: 'tobias',
    text: 'Can’t see my own feet in this. At my age that’s not a disaster. I know roughly where they are.',
    gist: 'couldn’t see his own feet in the fog',
    tags: ['fog', 'quiet', 'comfort'],
    hint: 'Tobias would like to know if anyone has seen his feet.',
    weather: ['foggy'],
  },
  {
    id: 'tobias_argue',
    resident: 'tobias',
    text: 'Barnaby and I haven’t argued properly in weeks. I’m worried he’s unwell.',
    gist: 'hadn’t argued with Barnaby in weeks',
    tags: ['social', 'play', 'rivalry'],
    hint: 'Barnaby and Tobias haven’t argued in weeks. People are concerned.',
    minDay: 2,
  },
  {
    id: 'tobias_teach',
    resident: 'tobias',
    text: 'The young ones don’t know how anything works any more. I’d like to fix that. One young one at a time.',
    gist: 'wanted to teach a young one how something works',
    tags: ['teach', 'curious', 'repair', 'social'],
    hint: 'Tobias has been explaining clocks to anyone who stands still.',
    minDay: 3,
  },
  {
    id: 'tobias_festival',
    resident: 'tobias',
    text: 'Lantern Night. I’d like to bring something that’ll get someone my age to dance. Or at least sway with intent.',
    gist: 'wanted to get someone his age to sway with intent',
    tags: ['festival', 'music', 'social'],
    hint: 'Tobias has polished his dancing shoes. Both of them.',
    day: 7,
  },
  {
    id: 'tobias_any',
    resident: 'tobias',
    text: 'Something to pass the afternoon. Something that’ll pass it slowly.',
    gist: 'wanted to pass the afternoon slowly',
    tags: ['quiet', 'comfort'],
    hint: 'Tobias has an afternoon to pass.',
    repeatable: true,
  },

  // ——— Margo ———
  {
    id: 'margo_glasshouse',
    resident: 'margo',
    text: 'The Glasshouse door’s been jammed since the spring storm. I’ve been growing tomatoes in a teapot.',
    gist: 'was growing tomatoes in a teapot because the Glasshouse door was jammed',
    tags: ['repair', 'grow', 'useful', 'nature'],
    hint: 'The Glasshouse door is still jammed. Margo’s teapots are full of tomatoes.',
    minDay: 2,
    maxDay: 6,
    locationClosed: 'glasshouse',
    priority: 3,
  },
  {
    id: 'margo_invite',
    resident: 'margo',
    text: 'I’ve been invited to a thing. With people. I’d like to bring something, so I’ve got somewhere to put my hands.',
    gist: 'needed something to bring to a thing, with people',
    tags: ['gift', 'social', 'food', 'courage'],
    hint: 'Margo has been invited somewhere and is taking it very seriously.',
    minDay: 2,
  },
  {
    id: 'margo_rain',
    resident: 'margo',
    text: 'Rain! Finally. The garden doesn’t need me today, which is insulting. I’ll find something else to fuss over.',
    gist: 'was insulted that the garden didn’t need her',
    tags: ['indoor', 'creative', 'rain', 'hobby'],
    hint: 'Margo is at a loose end, which is dangerous for everyone.',
    weather: ['rainy'],
  },
  {
    id: 'margo_poem',
    resident: 'margo',
    text: 'I’ve been writing something. It is not a poem. It has rhymes in it, but that’s a coincidence.',
    gist: 'was writing something that was definitely not a poem',
    tags: ['creative', 'quiet', 'courage', 'nature'],
    hint: 'Margo was seen counting syllables on her fingers.',
    minDay: 3,
  },
  {
    id: 'margo_wind',
    resident: 'margo',
    text: 'The wind’s trying to take my beans to the next village. I’m going out to shout at it.',
    gist: 'was going out to shout at the wind',
    tags: ['wind', 'outdoors', 'grow'],
    hint: 'Margo has declared war on the wind.',
    weather: ['windy'],
  },
  {
    id: 'margo_marrow',
    resident: 'margo',
    text: 'Barnaby’s been measuring my marrow when he thinks I’m not looking. I am always looking.',
    gist: 'had caught Barnaby measuring her marrow',
    tags: ['rivalry', 'grow', 'social'],
    hint: 'Someone has been measuring Margo’s marrow. She has suspicions. They are correct.',
    minDay: 3,
  },
  {
    id: 'margo_festival',
    resident: 'margo',
    text: 'I’m told festivals need “decoration.” I have a great deal of squash.',
    gist: 'had been told festivals need decoration',
    tags: ['festival', 'grow', 'gift'],
    hint: 'Margo is bringing squash to Lantern Night. A lot of squash.',
    day: 7,
  },
  {
    id: 'margo_any',
    resident: 'margo',
    text: 'Garden’s done. Weather’s behaving. Suspicious. I need a distraction.',
    gist: 'needed a distraction from suspiciously good weather',
    tags: ['hobby', 'outdoors'],
    hint: 'Margo is suspicious of the weather.',
    repeatable: true,
  },

  // ——— Hollis ———
  {
    id: 'hollis_hello',
    resident: 'hollis',
    text: 'Hello. I’m new. No. 3, Kettle Row. Sorry. I’d like to meet people — ideally without having to start the conversation.',
    gist: 'wanted to meet people without starting the conversation',
    tags: ['social', 'courage', 'host', 'gift', 'food'],
    hint: 'A removal cart was seen outside No. 3 Kettle Row at dawn.',
    day: 2,
  },
  {
    id: 'hollis_map',
    resident: 'hollis',
    text: 'I’m making a map of Mosswick. I’ve got the streets. I don’t have the good bits yet.',
    gist: 'was mapping the good bits of Mosswick',
    tags: ['curious', 'walk', 'adventure', 'creative', 'memory'],
    hint: 'The new mole has been measuring the Green with his feet.',
    minDay: 3,
  },
  {
    id: 'hollis_host',
    resident: 'hollis',
    text: 'I told someone they could come over tonight, which was very brave of Past Hollis. Present Hollis is less sure.',
    gist: 'had invited someone over, bravely',
    tags: ['host', 'social', 'indoor', 'food'],
    hint: 'Hollis has invited someone round and is now tidying at speed.',
    minDay: 3,
  },
  {
    id: 'hollis_rain',
    resident: 'hollis',
    text: 'Rain! Moles love rain. Everybody else hides, though, which is a shame.',
    gist: 'loved the rain, but everyone else was hiding',
    tags: ['rain', 'social', 'outdoors', 'walk'],
    hint: 'Hollis was seen standing happily in the rain.',
    weather: ['rainy'],
  },
  {
    id: 'hollis_dark',
    resident: 'hollis',
    text: 'I don’t mind the dark — I see about the same either way. I’d like to go somewhere everybody else finds exciting at night.',
    gist: 'wanted to go somewhere exciting after dark',
    tags: ['night', 'sky', 'adventure'],
    hint: 'Hollis asked what everybody “does up on that Hill.”',
    minDay: 3,
  },
  {
    id: 'hollis_step',
    resident: 'hollis',
    text: 'I’d like my front step to look like somebody lives there. Somebody nice.',
    gist: 'wanted his front step to look like somebody nice lived there',
    tags: ['grow', 'gift', 'creative', 'home'],
    hint: 'No. 3’s front step is looking very bare.',
    minDay: 3,
  },
  {
    id: 'hollis_festival',
    resident: 'hollis',
    text: 'My first Lantern Night. I’d like to bring something, so people know I meant to come.',
    gist: 'wanted people to know he’d meant to come',
    tags: ['festival', 'social', 'gift', 'courage'],
    hint: 'Hollis has asked three people what one wears to a Lantern Night.',
    day: 7,
  },
  {
    id: 'hollis_any',
    resident: 'hollis',
    text: 'I’d like to know Mosswick a little better, if that’s all right.',
    gist: 'wanted to know Mosswick a little better',
    tags: ['curious', 'social'],
    hint: 'Hollis is still learning his way around.',
    repeatable: true,
  },
]

export const REQUESTS_BY_ID: Record<string, RequestDef> = Object.fromEntries(REQUESTS.map((r) => [r.id, r]))
