import type { Pronouns, ResidentDef, ResidentId } from '../types'

const SHE: Pronouns = { they: 'she', them: 'her', their: 'her' }
const HE: Pronouns = { they: 'he', them: 'him', their: 'his' }

export const RESIDENTS: Record<ResidentId, ResidentDef> = {
  odile: {
    id: 'odile',
    name: 'Odile Fenn',
    short: 'Odile',
    species: 'Grey heron',
    pronouns: SHE,
    role: 'Postmistress',
    home: 'green',
    homeLabel: 'the flat above the Post Office',
    rhythm: 'Walks every lane in Mosswick before eight. Tea at four. Exactly four.',
    traits: ['precise', 'dry as a biscuit', 'secretly sentimental'],
    likes: ['fog', 'good handwriting', 'a well-folded map'],
    frets: [
      'Has no idea what to do with a free afternoon.',
      'Stands on one leg when thinking. Does not know she does it.',
    ],
    relations: {
      barnaby: 'Has delivered his post for twenty years. He offers her a scone every morning. She has never once stopped.',
      tansy: 'Keeps finding letters in the post box addressed to “The Moon, Up There.”',
      tobias: 'Admires his handwriting. Has said so exactly once, in 1998.',
    },
    secret:
      'Keeps every one of Tansy’s letters to the Moon in a drawer labelled UNDELIVERABLE (FOR NOW).',
    color: '#6f86a0',
    arrives: 1,
    social:
      '{name} wrote {other} a very correct note about it, delivered it by hand, and stayed for tea by accident.',
    react: {
      yes: ['Ah. Yes. That is — yes.', 'That will do very nicely indeed.', 'I had hoped you’d choose that. I didn’t hope out loud.'],
      hmm: ['{Obj}? Hm. I shall find a use for it. I always do.', 'Not what I pictured. Pictures are overrated.'],
      huh: ['{Obj}. For me. Well. I shall treat it as a puzzle.', 'I would never have chosen this. Which, I suppose, is the point.'],
    },
    decline: 'Nothing today? Then I shall walk the long way home and call it an outing.',
  },
  barnaby: {
    id: 'barnaby',
    name: 'Barnaby Holt',
    short: 'Barnaby',
    species: 'Badger',
    pronouns: HE,
    role: 'Baker at the Oven Door',
    home: 'green',
    homeLabel: 'the rooms behind the bakery',
    rhythm: 'Up at four for the loaves. Free by noon. Asleep by eight, mid-sentence.',
    traits: ['loud', 'generous', 'competitive about scones'],
    likes: ['brass bands', 'arguing about crosswords', 'rain on the bakery step'],
    frets: [
      'Has baked the same six loaves for eleven years and has started to notice.',
      'Goes completely to pieces around the postmistress.',
    ],
    relations: {
      tobias: 'His oldest friend. Tobias fixed the bakery clock in 1994. It still runs four minutes fast.',
      margo: 'Locked in a marrow rivalry that neither of them will admit to.',
      tansy: 'Gives her the burnt biscuits. She considers them the good ones.',
      odile: 'Says “morning” to her every day at nine. It is all he has managed to say in twenty years.',
    },
    secret: 'Has kept a notebook of new recipes for eleven years. He has never baked a single one.',
    color: '#b5523b',
    arrives: 1,
    social: '{name} turned up at {other}’s door with a warm loaf, which is how Barnaby says “I’d like to know you better.”',
    react: {
      yes: ['Now THAT’S the stuff!', 'Oh, that’s grand. That’s properly grand.', 'Ha! You read my mind. It’s mostly bread in there, so well done.'],
      hmm: ['{Obj}, eh? Go on then. I’m game.', 'Wouldn’t have thought of that. That’s why I came to you.'],
      huh: ['{Obj}? Ha! Why not. Worst case, I bake it a cake.', 'Right. RIGHT. No idea what I’ll do with it. Love it.'],
    },
    decline: 'Nothing on the shelf? Ah well. There’s always bread.',
  },
  tansy: {
    id: 'tansy',
    name: 'Tansy Burr',
    short: 'Tansy',
    species: 'Hedgehog, aged nine',
    pronouns: SHE,
    role: 'Investigator (self-appointed)',
    home: 'kettleRow',
    homeLabel: 'No. 2 Kettle Row',
    rhythm: 'School’s out for harvest week. Everywhere at once, asking questions.',
    traits: ['fearless in daylight', 'a collector of evidence', 'loud about it'],
    likes: ['the Moon', 'beetles', 'mud of any kind'],
    frets: [
      'Is a little bit scared of the dark, which is embarrassing for a hedgehog.',
      'Hates being told she is too small for things.',
    ],
    relations: {
      odile: 'Posts letters to the Moon. Has never received a reply. Keeps posting.',
      tobias: 'Pesters him for stories about the old days. He pretends to mind.',
      barnaby: 'Official taster of burnt biscuits.',
    },
    secret: 'Keeps a list titled THINGS I AM NOT SCARED OF. The Dark is on it, crossed out, then written in again.',
    color: '#e0a93b',
    arrives: 1,
    social: '{name} went straight round to {other}’s to ask eleven questions about it. {other} answered nine.',
    react: {
      yes: ['YES. Yes yes yes.', 'That’s EXACTLY the thing. How did you know?', 'I’ll be so careful with it. Mostly careful.'],
      hmm: ['Ooh. What does it do? Don’t tell me.', '{Obj}! I can work with {obj}.'],
      huh: ['That’s a weird choice and I love it.', 'I don’t know what it’s for yet, but it’ll be EVIDENCE of something.'],
    },
    decline: 'Nothing?! That’s fine. I’ll just go and look at a beetle. For AGES.',
  },
  tobias: {
    id: 'tobias',
    name: 'Tobias Crumb',
    short: 'Tobias',
    species: 'Tortoise, ninety-four',
    pronouns: HE,
    role: 'Retired clock-mender',
    home: 'kettleRow',
    homeLabel: 'No. 1 Kettle Row',
    rhythm: 'Newspaper on the Green at ten. Tinkering till three. Nap at three, sharp.',
    traits: ['patient', 'dryly funny', 'fussy about screwdrivers'],
    likes: ['old dance records', 'anything with gears', 'the long view from the Hill'],
    frets: [
      'Worries nobody needs anything mended any more.',
      'His hearing is going. He will not be telling anyone.',
    ],
    relations: {
      barnaby: 'Old friends. Their arguments are the most reliable thing in Mosswick.',
      tansy: 'Tells her stories about the old days. Some of them are even true.',
      margo: 'Thinks she is the only person in the village who listens properly.',
    },
    secret: 'His late wife Hettie once named a star after him. A very dim one. She said that was the point.',
    color: '#7b8448',
    arrives: 1,
    social: '{name} took the long way home, past {other}’s house — which for Tobias is a serious commitment — and knocked.',
    react: {
      yes: ['Ah. Now that’s a proper thing.', 'Oh, I remember these. Well — this one, specifically.', 'Lovely. Just lovely. I’ll bring it back before I forget I have it.'],
      hmm: ['Hm. Hm! Yes, I think I see.', 'Not what I’d have picked. That’s good. I’ve been picking my own things for ninety-odd years.'],
      huh: ['Goodness. Well. I’ll take it slowly.', '{Obj}. At my age, everything’s an adventure. I’ll let you know.'],
    },
    decline: 'Nothing today? Then I’ll have a sit on your bench, if it’s all the same.',
  },
  margo: {
    id: 'margo',
    name: 'Margo Sloe',
    short: 'Margo',
    species: 'Goat',
    pronouns: SHE,
    role: 'Keeper of the Glasshouse',
    home: 'glasshouse',
    homeLabel: 'the cottage by the Glasshouse',
    rhythm: 'Up with the sun. Argues with the weather until it gives in.',
    traits: ['blunt', 'practical', 'impatient with clouds'],
    likes: ['compost', 'frost on cabbages', 'being right about soil'],
    frets: [
      'The Glasshouse door has been jammed since the spring storm, and it is eating her alive.',
      'Suspects people find her prickly. (The actual hedgehog is fine.)',
    ],
    relations: {
      barnaby: 'Their marrows have been at war for three summers. Nobody remembers who started it. Both of them do.',
      tobias: 'The only person in Mosswick she lets win an argument.',
      tansy: 'Would like her to stop eating the peas straight off the vine.',
    },
    secret: 'Writes poems. About squash, mostly. There are forty of them. They rhyme.',
    color: '#5d7650',
    arrives: 1,
    social: '{name} told {other} it was “not bad,” which is Margo for “marvellous,” and stayed an hour.',
    react: {
      yes: ['Good. Sensible. Thank you.', 'That’ll do. That will more than do.', 'Right. I know exactly what I’m doing with that.'],
      hmm: ['Hm. Not bad. Not bad at all.', 'Wasn’t expecting that. I’ll allow it.'],
      huh: ['{Obj}? You’re a strange one. Fine.', 'I’ll either love it or write something strongly worded about it.'],
    },
    decline: 'Nothing. Fine. The garden always needs something shouting at.',
  },
  hollis: {
    id: 'hollis',
    name: 'Hollis Underfield',
    short: 'Hollis',
    species: 'Mole',
    pronouns: HE,
    role: 'Cartographer, newly arrived',
    home: 'kettleRow',
    homeLabel: 'No. 3 Kettle Row (new)',
    rhythm: 'Measures things in the morning. Apologises to them in the afternoon.',
    traits: ['earnest', 'formal', 'hopelessly curious'],
    likes: ['maps', 'puddings', 'knowing where everything is'],
    frets: [
      'Doesn’t know anybody yet. Worries he’ll be “the new mole” forever.',
      'Recognises people by their footsteps, which makes crowds very loud.',
    ],
    relations: {},
    secret: 'Has moved house nine times. Mosswick is the first place he has unpacked the box marked KEEP.',
    color: '#3f7a78',
    arrives: 2,
    social: '{name} knocked on {other}’s door, apologised to it, and then — bravely — knocked again.',
    react: {
      yes: ['Oh! Oh, that’s perfect. Sorry — thank you.', 'That’s — yes. Thank you. Very much. Sorry.', 'I’ll look after it like it’s a map.'],
      hmm: ['Oh. Interesting. I’ll — yes. I’ll think of something.', 'I wouldn’t have known to ask for that.'],
      huh: ['Right. Yes. I’ll, um. Yes.', 'I’m not sure what I’ll do with it, but I expect someone will show me.'],
    },
    decline: 'Oh — no, that’s quite all right. Sorry. I’ll come back.',
  },
}

export const residentList = (): ResidentDef[] => Object.values(RESIDENTS)
